### ISSUE TITLE
Spark Connectivity via Livy to avoid raw pyspark use

### ISSUE THREAD

**Issue by troxil** [fivetran/great_expectations#1223]
Hey All!

I very much love this project and also love Spark. Our current stack is Airflow + EMR for compute with S3 storage.

Commonly to do exploration I use Jupyterhub with sparkmagic to interface with that EMR cluster which runs anything in cells over Livy. This helps as the Jupyterhub server doesn't require pyspark installation, but merely makes API calls.

What I'd love to do is launch GE natively in Airflow (or via CLI) on my laptop and have all operations to my dataframes end up in EMR cluster. Pyspark can be used locally on EMR master to do this or as Jupyterhub sparkmagic does - via Livy API. 

Though with Livy it still means I may need GE to be installed over there. But I'm probably jumping to solution.

Let me know your thoughts!
Cheers

**Comment by jcampbell** [comment]
@troxil : one of my colleagues @alexsherstinsky has used just such a solution, which does involved installing GE on the cluster where you'll be running. I'll ping him to see if he can weigh in here.

**Comment by alexsherstinsky** [comment]
Hi @troxil -- great to hear from you.  The environment I used allowed GE to be installed as part of the EMR image; similarly to yours, our environment also had Jupyter (with the PySpark kernel) communicating with this Spark/EMR cluster over a Livy session.  However, I did not have Airflow in this set up.  Having said that, in order to execute GreatExpectations through Airflow, one would want to create one or two operators in Airflow (Python and/or Bash -- either of these or a combination would be fine, depending on the needs) and exercise these operators for the needed GreatExpectations functionality.  The challenge would be to make these GreatExpectations function calls not by importing great_expectations from the local Python environment, but as Livy API calls to the GreatExpectations installations in the Spark driver and executor nodes.  There is a PySpark example at `https://livy.incubator.apache.org/examples/` -- the experiment would involve having a Python code snippet that exercises a GreatExpectations function call and have it executed from inside a Python operator in Airflow.  The simplest test, in my opinion, would be to check the version of GreatExpectations that is part of the EMR image.  The code for that is two lines: import `great_expectations as ge` followed by `print(ge.__version__)` -- this code would be in the body of the Livy POST HTTP command, and the return value upon a successful completion of this Livy call would be the actual version of the GreatExpectations installed in the EMR cluster on AWS.  Please feel free to contact me on Slack (I am "alexsherstinsky" in the GreatExpectations Slack Workspace) to discuss this further.  I have outlined one possible approach, but there could be other/better ones.  So, by all means, please share with us the details of your configuration, when you ultimately get it to work!  Thank you very much!
