### ISSUE TITLE
Indenting Expectations to enable Pull Request Diff

### ISSUE THREAD

**Issue by troxil** [fivetran/great_expectations#1236]
Hi Team, 

I intend to use GE within a team environment. We will probably be storing them along side our project.
The expectations are stored in a single-lined JSON blob in your expectation store, but with no indentation and thus will make diffing the parameters challenging.

Any ideas on the best way to do pull requests with expectations?

Cheers

**Comment by Aylr** [comment]
@troxil First and foremost you are spot on storing `Expectations` in version control right in your project. 🎉 

We have discussed this as a feature we all want for the exact same reasons. We had held off initially because getting ordered dicts in legacy python was squirrelly at best. But now that we have dropped legacy python support there are no blockers to this important feature.

We'd love a PR if you are so inclined. If this is something you want to contribute to it would be a great first issue!

If not, a workaround we've used in the past is to open your json files with an ide like Atom and use a deterministic JSON prettyfier before you commit them.
