### ISSUE TITLE
expect_column_values_to_not_be_null sees empty strings as values

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1535]
**Describe the bug**
Where there are empty strings in a database field, the expectations of non nullity **actively deceive users.**

**To Reproduce**
1. Create an expectation of nullity like:
```python
batch.expect_column_values_to_be_null("mystery_field")
```
2. evaluate the expectation
3. Breathe a sigh of relief that you've protected your pipeline from missing data in this field
4. Later find out that there is in fact no data in this field. Only empty strings.

**Expected behavior**
I would expect an empty string to be seen as a null value.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS against a BigQuery datasource (though I've seen this on other datasources)
 - GE Version: [e.g. 0.10.0] 0.11.1

**Additional context**

Right now, I am using a workaround by using `expect_column_values_to_not_be_in_set` but this isn't documenting data very nicely. Furthermore it's impossible to read in datadocs that the expected set is only a single empty space.

<img width="676" alt="JupyterLab" src="https://user-images.githubusercontent.com/928247/83578103-2ac84e80-a4f3-11ea-9fe7-16b5fcb912c4.png">

**Comment by Aylr** [comment]
This probably calls for a new expectation type like
```python
expect_column_values_to_not_be_missing("id", semantically_missing=["", "n/a",])
```

**Comment by elsander** [comment]
I'm happy to take a stab at this one. I can see a couple possible implementations:

1. Add an argument to `expect_columns_to_be_null` (and the inverse) to accept additional values which should be treated as null.
2. Create a new expectation `expect_column_values_to_be_missing` (as well as an inverse) which checks for a list of values which should be treated as null/missing. This seems like a fairly straightforward wrapper around `expect_columns_to_be_in_set` as mentioned in the ticket.
3. Same as 2, but have some default behavior which checks for nulls in addition to user-provided values. This distinguishes the functionality from `expect_columns_to_be_in_set`, but I don't necessarily find it an intuitive behavior (since "missing" is a more general term than "null"). I'm happy to implement this if it's intuitive to others.
4. Something else I'm not thinking of.

@Aylr , which of these seems most aligned with GE's design principles?

**Comment by Aylr** [comment]
Amazing! I can't decide which makes more sense between 1 or 2 - I don't have a strong opinion here perhaps @eugmandel could sway us one way or the other.

**Comment by elsander** [comment]
I'm looking at this again, and GE already treats "missing" as synonymous with "null" (since there is a "missing_count" and "missing_percent" in the output keys). It would be confusing to have a "null" expectation and a "missing" expectation if they're treated as synonymous elsewhere. So what makes the most sense to me is option 1, adding an optional `treat_as_null` argument. I'll start with that but, but happy to switch to a different approach if that's better.

This does open up a can of worms-- should those values be added to the "missing_count" and "missing_percent"? If so, what does this mean for reported missingness in the other expectations, where only null is treated as missing? Basically, the values that define missingness are a property of a column, but only `null` is assumed to define missingness across expectations. For consistency with the other expectations, I think I'll omit non-null values from the missing count, but include them in the unexpected count.

**Comment by Aylr** [comment]
In absence of another opinion I think your approach here makes tons of sense.

Regarding the can of worms... I _think_ adding those to `missing_*` makes sense because the user would be specifically including additional "semantic null" values. As far as the other expectations go... yikes, I'd want to think about that more. I'd say proceed and see what shakes out for now.

PS I'm **stoooooooked** you're picking this up.
