### ISSUE TITLE
Snowflake SSO authentication

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#1629]
**Is your feature request related to a problem? Please describe.**

In our org we use SSO to authenticate users to Snowflake, other means of authentication are only used for non-human processes

**Describe the solution you'd like**

I would like GE to support using SSO as a means of authentication, in a similar fashion as DBT: https://docs.getdbt.com/docs/supported-databases/profile-snowflake/#sso-authentication

**Describe alternatives you've considered**

We will use another way of authenticating for the time being

**Comment by armaandhull** [comment]
@dmateusp an alternative approach based on Snowflake's RBAC is to set up a machine USER/ROLE that has:

- READ permissions on all relevant tables/schemas in your database
- CREATE table privileges in 1 schema e.g. `database_name.ge_schema` (since it needs to create a transient table for expectation suite)
- Grant usage of that ROLE to human users/roles

You can share the creds via a config server/LastPass and then use those while developing expectations locally.

**Comment by dmateusp** [comment]
Thanks Armaan, I think we could also assign the role as part of SSO authentication, the problem is really with having a user/password in the first place, or using SSH keys
