### ISSUE TITLE
expect_column_values_to_not_be_null returns wrong unexpected_count

### ISSUE THREAD

**Issue by shiva-z** [fivetran/great_expectations#1724]
**Describe the bug**
for a dataframe with no null values `expect_column_values_to_not_be_null` returns a result with `success=True` but `unexpected_count` is not zero.

**To Reproduce**
```
import pandas as pd
import great_expectations as ge
data = ge.from_pandas(pd.DataFrame([[1],[2],[3]], columns=['a']))
data.expect_column_values_to_not_be_null(['a'])
```
Result:
```
{
  "meta": {},
  "exception_info": null,
  "success": true,
  "result": {
    "element_count": 3,
    "unexpected_count": 1,
    "unexpected_percent": 33.33333333333333,
    "partial_unexpected_list": []
  }
}
```
**Expected behavior**
```
{
  "meta": {},
  "exception_info": null,
  "success": true,
  "result": {
    "element_count": 3,
    "unexpected_count": 0,
    "unexpected_percent": 0,
    "partial_unexpected_list": []
  }
}
```
**Environment (please complete the following information):**
 - OS: macOS
 - GE Version: 0.11.8

**Comment by talagluck** [comment]
Great catch! The column specified in `data.expect_column_values_to_not_be_null(['a'])` above is in a list. When specifying the column in an expectation, it should be a string - so `'a'` rather than `['a']`. 

I'm looking into what is actually happening when a list is passed in - we either need a better error message, or different functionality.
