### ISSUE TITLE
The timestamp on slack messages does not correspond with the validation run time.

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1738]
**Describe the bug**
The timestamp on slack messages does not correspond with the validation run time.

**To Reproduce**
1. Run a validation operator that has a slack action
2. Find the slack message
3. Note the discrepancy

**Expected behavior**
I expect the timestamp to either be the same as the run ID run time or **be removed since it is now obsolete?**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.11.8

**Additional context**
Here are two messages where it's obvious the timestamp is not correct. It looks like it might be the time the slack message was sent.

<img width="800" alt="Slack___notifications-data-quality___BERA_Brand_Management" src="https://user-images.githubusercontent.com/928247/88725008-a952fe00-d0e8-11ea-8872-da3f59eef43a.png">

**Comment by Shinnnyshinshin** [comment]
@Aylr you're right, the `Timestamp` is calculated as the time that the Slack message is sent. I'm ok with removing the field entirely, since the `run_time` provides information on when the Validation ran, and Slack already has a timestamp associated with each message. I'll try to package this change with the a Slack-related PR I've been working on.

**Comment by Shinnnyshinshin** [comment]
closed by #1707
