### ISSUE TITLE
Add support for BigQuery partitioned tables

### ISSUE THREAD

**Issue by inferrinizzard** [fivetran/great_expectations#1783]
**Is your feature request related to a problem? Please describe.**
Getting batches and running expectations fails for any BigQuery table that requires a partition filter as it will throw an error without it.

**Describe the solution you'd like**
Ideal solution is ability to pass an optional argument to batch_kwargs that adds a WHERE clause to the initial batch query to prevent error and then additional expectations can be dealt with via custom expectations.

**Describe alternatives you've considered**
A potential workaround would be to create views of the particular table you want to query and run great expectations on that but it is not feasible as it only provides 1 instance of 1 filter and cannot easily be changed. Doing that multiple times for multiple tables is untenable.

**Additional context**
See  https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1596472193025800

**Comment by dlamblin** [comment]
It's still relevant to me afaics (point me to documented work arounds if I'm missing any):
https://stackoverflow.com/questions/75622192/how-can-i-force-a-partition-filter-to-be-added-to-a-great-expectations-dataset

The one workaround that isn't in play is:
```sql
ALTER TABLE IF EXISTS theDataset.theLargePartitionedTable
SET OPTIONS(
    require_partition_filter = false
)
```

**Comment by cwdjankoski** [comment]
Hi @dlamblin - i am having the same use-case and troubles, tried out several things that were suggested in the GX [community slack](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1674751988567679?thread_ts=1674506882.179459&cid=CUTCNHN82
) but unfortunately without success.  
Thought to post here in hope that perhaps someone can advise on how to do this properly + 1 workaround that my friend @nadalal ( cannot tag her here somehow ) found.  

As suggested in that slack conv - there are `Splitter` methods described in [this documentation page](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql/)  
"How to configure a DataConnector for splitting and sampling tables in SQL"  

I tried to get this to work with my setup in BQ but sadly to no success. The setup is quite simple  - we have a table in BQ that is partitioned on a timestamp column. The partition filter is required and one cannot query over the table without specifying a filter condition on that column.  
I tried out the code/setup that page suggests but was not able to make it work. I am also not 100% sure that this method is supposed to work with partitioned tables - so maybe someone more knowledgable can chip in here (because there are 2 comments in the community slack saying this _"may help you with your problem"_ ... not sure how to interpret the "may" here)  

<details>
  <summary>Code</summary>

 ```python
from ruamel import yaml

import great_expectations as gx
from great_expectations.core.batch import BatchRequest

datasource_yaml = f"""
name: MY-BQ-DATASOURCE-GX-EXAMPLE
class_name: SimpleSqlalchemyDatasource
connection_string: bigquery://MY-BQ-PROJECT-STRING

introspection:  # Each key in the "introspection" section is an InferredAssetSqlDataConnector
    whole_table:
        include_schema_name: true
        introspection_directives:
            include_views: false
        skip_inapplicable_tables: true  # skip and continue upon encountering introspection errors
        included_tables:  # a list of tables to ignore when inferring data asset_names
            - MY-DATASET.MY-PARTITIONED-TABLE  # format: schema_name.table_name

    daily:
        introspection_directives:
            include_views: true
        skip_inapplicable_tables: true  # skip and continue upon encountering introspection errors
        include_schema_name: true
        included_tables:  # only include tables in this list when inferring data asset_names
            - MY-DATASET.MY-PARTITIONED-TABLE  # format: schema_name.table_name
        splitter_method: split_on_year_and_month_and_day
        splitter_kwargs:
            column_name: MY-PARTITIONING-COLUMN

    hourly:
        introspection_directives:
            include_views: true
        skip_inapplicable_tables: true
        include_schema_name: true
        included_tables:  # only include tables in this list when inferring data asset_names
            - MY-DATASET.MY-PARTITIONED-TABLE  # format: schema_name.table_name
        splitter_method: split_on_converted_datetime
        splitter_kwargs:
            column_name: MY-PARTITIONING-COLUMN
            date_format_string: "%Y-%m-%d %H"

tables:  # Each key in the "tables" section is a table_name (key name "tables" in "SimpleSqlalchemyDatasource" configuration is reserved).
    # data_asset_name is: concatenate(data_asset_name_prefix, schema_name, table_name, data_asset_name_suffix)
    hbo_events:  # Must match table name exactly.
        partitioners:  # Each key in the "partitioners" sub-section the name of a ConfiguredAssetSqlDataConnector (key name "partitioners" in "SimpleSqlalchemyDatasource" configuration is reserved).
            whole_table:
                include_schema_name: true
                schema_name: MY-DATASET
                data_asset_name_prefix: testgx__ 
                data_asset_name_suffix: __asset
                
            by_partition_date:
                include_schema_name: true
                schema_name: MY-DATASET
                data_asset_name_prefix: testgx__
                data_asset_name_suffix: __asset
                splitter_method: split_on_year_and_month_and_day
                splitter_kwargs:
                    column_name: MY-PARTITIONING-COLUMN
"""

context = gx.get_context()

context.test_yaml_config(datasource_yaml)

context.add_datasource(**yaml.load(datasource_yaml))

# Attempting to instantiate class from config...
# 	Instantiating as a Datasource, since class_name is SimpleSqlalchemyDatasource
# 	Successfully instantiated SimpleSqlalchemyDatasource

# The output of this ^^ is: -------------
#
# ExecutionEngine class name: SqlAlchemyExecutionEngine
# Data Connectors:
# 	daily : InferredAssetSqlDataConnector
#
# 	Available data_asset_names (0 of 0):
#
# 	Unmatched data_references (0 of 0):[]
#
# 	hourly : InferredAssetSqlDataConnector
#
# 	Available data_asset_names (0 of 0):
#
# 	Unmatched data_references (0 of 0):[]
#
# 	whole_table : InferredAssetSqlDataConnector
#
# 	Available data_asset_names (1 of 1):
# 		testgx__MY-DATASET.MY-PARTITIONED-TABLE__asset (1 of 1): [{}]
#
# 	Unmatched data_references (0 of 0):[]
#
# ------------------


# Here is a BatchRequest naming an inferred data_asset partitioned by day.
# This BatchRequest specifies multiple batches, which is useful for dataset exploration.
batch_request = BatchRequest(
    datasource_name="MY-BQ-DATASOURCE-GX-EXAMPLE",
    data_connector_name="hourly",                 # <-------- TRIED DIFFERENT THINGS HERE
    data_asset_name="MY-DATASET.MY-PARTITIONED-TABLE",
)
#
# but also tried with { daily , hourly , by_source_timestamp_date }
# as arg for `data_connector_name`

batch_list = context.get_batch_list(batch_request=batch_request)
```
</details>

And if i try:
  - `{daily|hourly}` as `data_connector_name` i get error of type "data_asset_name is not recognized"
```python
KeyError: 'data_asset_name MY-DATASET.MY-PARTITIONED-TABLE is not recognized.'
```

  - `by_partition_date` as `data_connector_name` i get the "partition column required errors"
```python
DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Cannot query over table 'THE-DATASET.THE-TABLE' without a filter over column(s) 'THE-PARTITION-COLUMN' that can be used for partition elimination
```

So i am wondering what is the correct and expected way to use this setup in order to achieve checks on partitions ? To be honest - the documenation is not the easiest to understand and is kind of split between that page and this [example script](https://github.com/great-expectations/great_expectations/blob/develop/tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/sql_database/yaml_example_complete.py#L35).  
Hopefully we manage to sort this out - and I will be more than happy to help / contribute to improve the documentation and examples.  

#### Workaround
My friend @nadalal did find a workaround about this. You have to setup the datasource as usual via the cmd line and then create a new expectation suite also via:
```python
great_expectations suite new
```
But then replace the `BatchRequest` with this `RunTimeBatchRequest`
```python
runtime_batch_request = RuntimeBatchRequest(
    datasource_name=MY-DATASET,
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name=MY-TABLE,
    runtime_parameters={"query": 'SELECT * from MY-DATASET.MY-TABLE WHERE {PARTITIONING_DATE_FIELD_NAME}="2022-11-01"'},
    batch_identifiers={"default_identifier_name": "default_identifier"},
)
```  

This seems to work as expected and does checks only on 1 partition of your data.  

Hope this helps and hope to get someone more knowledgable from the team or contributors to explain a bit more on how those `Splitter` approach is supposed to work. Please let me know if i can provide some more context or information. Would be very grateful for any thoughts and help.

**Comment by dlamblin** [comment]
Thanks, I actually don't want to switch to a RunTimeBatchRequest with a query. I do know that could work around it. I am also currently trying to make a view with a date in the where clause relative to current date, against which I'd specify the BatchRequest using the ConfiguredAssetSqlDataConnector to effectively force the inclusion of a partition specifier that way.

**Comment by Chr96er** [comment]
This is still an issue and prevents people from using GX in projects with BQ partition filter enforcement, which I would put on any sufficiently fairly large table that is being used outside of pipelines, e.g. by end user running SQL, APIs, BI tools.

**edit: I was trying to get RunTimeBatchRequests to work but I can't find documentation for v0.17.0 or how to make this work with fluent_datasources.**

**Comment by cwdjankoski** [comment]
I would also like to restart the conversation on this issue, if possible. I'm happy to help, contribute and help with testing but i am not so knowledgable in the code base to be able to contribute meaningful features.
BQ partitioned tables are - as @Chr96er says - very wide-spread and having an easy and straightforward way to run GX against them would be a very valuable option.
Alternatively - if someone could guide me on how to do this via some less easy and more involved way - I'm happy to learn and write this down and contribute it to the official documentation so that it helps other people in similar situation like me.

Thank you in advance, keep up the great work !
