### ISSUE TITLE
Does not show the website after creating the html doc

### ISSUE THREAD

**Issue by khuyentran1401** [fivetran/great_expectations#1816]
I followed the instruction here: https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/set_up_data_docs.html#tutorials-getting-started-set-up-data-docs. 

When the terminal asks: Would you like to view your new Expectations in Data Docs? This will open a new browser window. [Y/n]: . I chose Y and nothing shows up.

**Comment by eugmandel** [comment]
@khuyentran1401 Could you please provide more details:
* Version of Great Expectations
* Your environment: Windows/OSX/Linux, a dockerized environment? 
* Which browser are you using

Thank you!

**Comment by cmdkeen** [comment]
This happened for me using:

- great-expectations==0.13.4
- WSL2
- Chrome

Error message: 403 GET /files/data_docs/local_site/expectations/taxi/demo.html (127.0.0.1): Blocking request from unknown origin

Switching to using Edge as the browser worked fine.

**Comment by cbuffett** [comment]
I'm running into a slightly related issue using WSL2 when attempting to load the data docs after running the scaffolded taxi.demo

```
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "file:///mnt/c/venv/ge_example/great_expectations/uncommitted/d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
The same thing happens if I try to re-init the project when it asks me to build the data docs

```
This looks like an existing project that appears complete! You are ready to roll.


Great Expectations added some missing files required to run.
  - You may see new files in `great_expectations/uncommitted`.
  - You may need to add secrets to `great_expectations/uncommitted/config_variables.yml` to finish onboarding.

Would you like to build & view this project's Data Docs!? [Y/n]: y

The following Data Docs sites will be built:

 - local_site: file:///mnt/c/venv/ge_example/great_expectations/uncommitted/data_docs/local_site/index.html

Would you like to proceed? [Y/n]: y

Building Data Docs...

Done building Data Docs
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "file:///mnt/c/venv/ge_example/great_expectations/uncommitted/d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

I had the same issue show up when attempting to launch the notebook in Jupyter, but was able to get around that by setting `c.NotebookApp.use_redirect_file = False` in `~/.jupyter/jupyter_notebook_config.py`

I'm on version 0.13.10, Ubuntu 20.04 running under WSL2, and using Chrome.

**Update**
I tried setting up Chrome in WLS2 using `export BROWSER='/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe'`, but when the data docs are launched, Chrome is trying to open `file:///mnt/c/venv/ge_example/great_expectations/uncommitted/data_docs/local_site/index.html`, which fails.

I suspect that the BROWSER environment variable is not being double-quoted as running `"$BROWSER" great_expectations/uncommitted/data_docs/local_site/index.html` correctly opens the file
