### ISSUE TITLE
Building Data Docs can be slow

### ISSUE THREAD

**Issue by anthonyburdi** [fivetran/great_expectations#1826]
**Describe the bug**
Building Data Docs when there are many validations can be slow (minutes+)

**To Reproduce**
1. Create a GE sandbox install
2. Run a validation programatically at least hundreds of times
3. Build data docs

**Expected behavior**
Expect that data docs builds more quickly, or potentially automatically skips rendering older validations (e.g. the validation_results_limit option has a default)

**Environment (please complete the following information):**
 - GE Version: [e.g. 0.10.0]

**Additional context**
https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1597670466008100

**Comment by omriAl** [comment]
@anthonyburdi Hi, I want to take a look on this issue, but unfortunately I can't see the slack message that discusses this.
Can you please upload here the relevant details (if they exist)
Thanks.

**Comment by omriAl** [comment]
After inspecting the code I see that in `great_expectations/validation_operators/validation_operators.py:309` we are basically performing all of the actions (including data docs updates) after each validation asset.
While I expect this will improve the runtime, I don't think that this is the root cause.
I will take a better look on the TupleS3StoreBackend class further, and see how we can improve it (maybe by caching instead of listing multiple S3 keys for every update).

**Comment by talagluck** [comment]
Hi @omriAl ! Thanks for jumping in here. This issue had been closed a few months ago, and has been addressed by #2100. Is this still an issue for you? Or are you looking for other issues to help contribute? If this is still an issue for you, please feel free to open a new GitHub issue. If you are looking to contribute, I would invite you to take a look at any open issues that have a help-wanted tag.

Thank you!
