### ISSUE TITLE
Ability to register multiple expectations of the same type and column

### ISSUE THREAD

**Issue by mirosval** [fivetran/great_expectations#1879]
**Is your feature request related to a problem? Please describe.**
I have a column that looks like this `segment_a.segment_b.segment_n.action` and I would like to validate that:
1) `segment_a` is always from a specific list AND (
2) `a.b`, given that `segment_a` is of a specific value, `segment_b` is from a specific list OR
3) `b.c` given that `segment_a` is of a specific value, `segment_b` is from a different specific list ) AND
4) `action` is from a list

This use case does not fit either of the regex list type expectations, because those are either (AND or OR). So I can not define these groups of expectations, where the regex matches either exactly one from one group, OR exactly one from another group AND exactly one from a third group. I hope this is understandable.

**Describe the solution you'd like**
I would like to be able to define multiple named expectations for a column, that way I could define each of (1-4) as a separate expectation. From my digging around the code it seems that the data structure would support this, but the tools such as the Jupyter Notebook will always write only the last one of multiple expectations for a column.

**Describe alternatives you've considered**
The solution I'm using now is to create multiple expectation suites, where the 'given that`segment_a`' part is handled by a where clause of a sql query.
I've considered creating my own expectation, but it seemed too cumbersome to then describe multiple groups of regexes in the parameters. It would also not be very readable if something goes wrong.
Another solution would be to actually cram all these requirements into a single regex, but I think with the amount of segments in the first 2 positions (close to a hundred) this would quickly become unreadable and unmaintainable. Especially since there are ANDs and ORs between different subgroups.

**Additional context**
Originally I didn't want to create this issue, because I saw some related discussion about multiple expectations for the some column where the idea was dismissed, but I was asked to create an issue on Slack.

**Comment by spbail** [comment]
Hi @mirosval, thanks for submitting the issue, appreciate it! We hear you, this is definitely a good point to bring up and a relevant use case for allowing multiple expectations on a single column. 

It sounds like this was already discussed in Slack, but just to capture it here: We agree that this would be a really useful capability in Great Expectations. On the other hand, it's a pretty big departure from how expectations are designed at the moment, so it's something that we'll have to plan out and understand the implications of. Since there's a workaround (creating multiple expectation suites), this isn't top priority for us right now, but we will definitely revisit at a later point. Again, thanks for bringing this up and submitting the issue, this is really helpful input for us!
