### ISSUE TITLE
Images on Data Docs walkthrough are broken when hosted on GCS

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1943]
**Describe the bug**
Images on Data Docs walkthrough are broken when hosted on GCS via an AppEngine proxy

**To Reproduce**
1. Set up GCS bucket to host data docs
2. Set up an AppEngine proxy as documented in RTD
3. `great_expectations docs build`
4. Open site and note no images are present on the walkthrough.

**Expected behavior**
I expect to see images.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOs
 - GE Version: [e.g. 0.10.0] 0.12.3

**Comment by eugmandel** [comment]
The core team will look into this issue. Any additional information from users who encounter this issue will be very useful (e.g., AppEngine logs).

**Comment by noklam** [comment]
I think even in local the images are broken. From what i notice, the index.html page can render correctly. Once you click into some validation those images are broken because the path is wrong.

The href in those HTML are missing one less `../`, my adhoc solution is to just copy the static folder into the validations folder.

**Comment by jakeberesford-palmetto** [comment]
I just ran into this same issue. The problem is that flask applications expect assets in `/static` to exist within a `/static` directory on the server. Flask bypasses routing for static assets, so the images in /static cannot be retrieved from GCS.

The solution is to set `static_folder=None` when you instantiate the Flask application like this:

```
app = Flask(__name__, static_folder=None)
```

This allows the /static paths to be routed through the application and retrieved from the GCS bucket.
