### ISSUE TITLE
User should be able to auto-generate an expectation from a test written in SQL

### ISSUE THREAD

**Issue by eugmandel** [fivetran/great_expectations#2004]
Currently you must use Python and SQLAlchemy to create a new expectation that can be used against a database.

There’s a whole community of data analysts and scientists who would love to author new/custom expectations that can run against their databases for whom SQL is the primary language.

There should be a way to translate a SQL query into a new expectation without writing any Python.

**Comment by grauscher** [comment]
Would it be possible to do that by creating some kind of "custom expectation factory", that receives the custom query and outputs the custom expectation as a class/function?

**Comment by bhcastleton** [comment]
I changed the name of this issue to avoid confusion. We've had some people think this issue was about putting expectations on a custom sql dataset. That's not what this issue is about. That can be done currently using a custom sql query as a runtime parameter in validation. This issue is about auto-generating GE expectations from tests written in sql.

**Comment by viniciusdsmello** [comment]
Hi, I've found this issue during a search for the same issue. Here we want to translate some business rules to expectations, it would be great to build an expectation based on a SQL (i.e. columns created based on some SQL logic) query without the need to create a view only to do it. Does anyone have any news about it?
