### ISSUE TITLE
[Bug] dynamic sqlalchemy query stores returns a list

### ISSUE THREAD

**Issue by itsAlexK** [fivetran/great_expectations#2033]
**Describe the bug**

dynamic sqlalchemy query stores returns a list rather than a single value.  For example I'm expecting `500` but am getting `5000`

**To Reproduce**

setting up the expectation store:
```python
                "my_query_store": {
                    "class_name": "SqlAlchemyQueryStore",
                    "credentials": credential_args,
                    "queries": {
                        "row_counts": "SELECT count(*) as row_counts FROM a_table;"
                    }
                }
```

when validating against a batch
```python
batch.expect_table_row_count_to_be_between(
    min_value=0,
    max_value={"$PARAMETER": "urn:great_expectations:stores:my_query_store:row_counts"}
)
```
**Expected behavior**

the expected max_value should be an integer retrieved from the query

**Environment**
 - OS: MacOS Catalina 10.15.6
 - GE Version: 0.12.7

**Additional context**

slack conversation: 
https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1604075183282800

I think its due to how the query results are being parsed.

```python
# in eval parameters
            res = ge_urn.parseString(L[0])
            if res["urn_type"] == "stores":
                store = data_context.stores.get(res["store_name"])
                return store.get_query_result(
                    res["metric_name"], res.get("metric_kwargs", {})
                )
```

```python
# in query stores 
    def get_query_result(self, key, query_parameters=None):
        if query_parameters is None:
            query_parameters = {}
        query = self._store_backend.get(self._convert_key(key).to_tuple())
        query = Template(query).safe_substitute(query_parameters)
        res = self.engine.execute(query).fetchall()
        # NOTE: 20200617 - JPC: this approach is probably overly opinionated, but we can
        # adjust based on specific user requests
        res = [val for row in res for val in row]
        return res
```

**Comment by eugmandel** [comment]
@itsAlexK Thank you for reporting this! We will follow your steps to reproduce and will take it from there.

**Comment by eugmandel** [comment]
@itsAlexK The issue is reproduced and acknowledged as a bug. The value returned from by queries in a query story always appears as a list.  

We will spec and implement a fix. Since some queries return lists (e.g., a set of values for expect_column_values_to_be_in_set expectation that is used as an example in the [how-to guide](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_dynamically_load_evaluation_parameters_from_a_database.html)) while others queries return a scalar, we might need to add a config property that will allow the user to define the return type of a query.
