### ISSUE TITLE
basic functionality such as scaffold stuck on execution for Teradata

### ISSUE THREAD

**Issue by ausiddiqui** [fivetran/great_expectations#2043]
**Describe the bug**
Generated a datasource to Teradata using SQLAlchemy but unable to carry out any of the functionality. The new profile, `suite scaffold` and `suite edit` commands just remain stuck on the CLI for hours without any output or interaction. 

**To Reproduce**
1. In a brand new Python 3.7 conda environment installed great_expectations followed by `teradatasqlalchemy`. Ran `great_expectations init` and then Setup a SQLAlchemy connection string of the following format: `teradatasql://<username>:<password>@<server.domain.com>`. Received the "Great Expectations connected to your database!" message.
2. Answered 'Y' to "Would you like to profile new Expectations for a single data asset within your new Datasource? [Y/n]"
3. The process seemed stuck with no feedback for a few hours before I terminated it using ctrl+z.
4. Same thing happened on running `great_expectations suite scaffold my_suite_name`. Only received the following on text:
"Heads up! This feature is Experimental. It may change. Please give us your feedback!"
5. Same thing happened on running `great_expectations suite edit my_suite_name`. Received the following text:
"A batch of data is required to edit the suite - let's help you to specify it."

**Expected behavior**
Expected more configuration options to appear to ask for input or for results to appear or some indication that the program is running with intermediary results or progress information.

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - GE Version: 0.12.7

**Comment by eugmandel** [comment]
@ausiddiqui Thank you for reporting this issue!

Teradata is not fully supported by Great Expectations yet, meaning that we have not tested against it: https://github.com/great-expectations/great_expectations/issues/1969

We would love to find community contributors to make Teradata fully work, since users who work with a particular database engine are the best candidates to make these fixes. Is this something you would be interested in? If yes, we will support you through the process of creating and reviewing the PR.
