### ISSUE TITLE
Add an expectation for column order (e.g. column A should be first; column B should be second; etc.)

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#214]
Not sure if this should go into `expect_column_to_exist`, or a new expectation. But we should have it.

**Comment by louispotok** [comment]
I think it makes sense to add a kwarg to `expect_column_to_exist`. If I'm reading the code correctly, how about something like the following:

```
def expect_column_to_exist(
        self, column, 
        column_idx=None, # new
        result_format=None, include_config=False, 
        catch_exceptions=None, meta=None
):

    if column in self:
        return {
            "success": (column_idx is None) or (self.columns.get_loc(column) == column_idx)
        }

    else:
        return {
            "success": False
        }

```

**Comment by abegong** [comment]
That'd be awesome! Could you submit it as a PR?

**Comment by louispotok** [comment]
Done! Two questions / confusions about the test suite, which I can create issues for if helpful. Broadly, is there some special way you are running the tests or just `python -m unittest`?

1. I changed **one** test (in test_pandas_dataset.py) so it would fail, and ran the full test suite using `python -m unittest`. The output showed me that there were **two** failures. However, running only the tests in test_pandas_dataset.py showed just one failure. Do you know why this might be?
2. The failure message was fairly unhelpful, eg:
```
======================================================================
FAIL: test_expect_column_to_exist (tests.test_pandas_dataset.TestPandasDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/louispotok/great_expectations/tests/test_pandas_dataset.py", line 28, in test_expect_column_to_exist
    self.assertEqual(out, t['out'])
AssertionError: {'success': False} != {'success': True}
- {'success': False}
?             ^^^^

+ {'success': True}
?             ^^^

```
Notice this does not show me *which* test case failed. I think this is due to the test style of `for c in cases: assertEquals(f(c["in"]), c["out"])`. One way to fix this would be to pass c["notes"] to `assertEquals` every time, but this is just more boilerplate. Have you encountered this, or do you have other thoughts?

**Comment by abegong** [comment]
We're using `pytest` because of exactly the problem you ran into.

Yes, failure messages for the JSON are lousy right now.

Thanks for sharing what you're seeing. Look for more discussion and a proposal to tidy things up soon---we'd love to get your feedback on that when it's closer.

**Comment by louispotok** [comment]
Interesting! I wonder why unittest is discovering them twice. `pytest` is working for me. As I commented elsewhere, if `pytest` is recommended, it should maybe go in requirements-dev as well. Failure messages are important, but it sounds like they are being discussed in #167 .

Anyway, I think this issue can be closed. Thanks for the quick replies!

**Comment by jpcampb2** [comment]
I brought this implementation across for the new sqlalchemydataset as well. Can we close this issue?

**Comment by abegong** [comment]
Yes!
