### ISSUE TITLE
Issue: "InternalError: (pymysql.err.InternalError) (1137, "Can't reopen table: 'ge_tmp_2ea7f209'")" while executing the provided "Run the Scaffolder" commands

### ISSUE THREAD

**Issue by RamishaMunir** [fivetran/great_expectations#2199]
**Steps to reproduce the error:**
1. Connect to MySQL database using great_expectations CLI
2. it will ask "which table would you like to choose", Type a query to pick the table
3. it will open Jupyter with some pre-commands to run. When you'll run the Scaffolder (screenshot is attached), it will throw the exception stating "InternalError: (pymysql.err.InternalError) (1137, "Can't reopen table: 'ge_tmp_2ea7f209'")"
![image](https://user-images.githubusercontent.com/33277708/102716449-d73a1880-42fd-11eb-942a-f055484c2d16.png)

**Great-expectations Version:** 0.13.3
**MySQL version:** 5.7.14

**Comment by eugmandel** [comment]
Thank you for reporting this, @RamishaMunir ! Most likely, this happens when the profiler attempts to run the `expect_column_values_to_be_unique` expectation on this table. The ""Can't reopen table:" error message points to a known MySQL limitation. 

A similar issue was reported here:
https://github.com/great-expectations/great_expectations/issues/1862

We will discuss how to fix it.

**Comment by RamishaMunir** [comment]
@eugmandel if this is the case that it attempts to run `expect_column_values_to_be_unique` expectation then it should let the user decide if this expectation is actually needed or not rather than raising an exception by deciding on itself
