### ISSUE TITLE
Could "great_expectations project upgrade" update the "great_expectations_version" field?

### ISSUE THREAD

**Issue by marhoy** [fivetran/great_expectations#2333]
After upgrading great_expectations to a new version, I get a lot of warnings like:
```
UserWarning: WARNING: This configuration object was built using version 0.13.4 of great_expectations, but is currently being validated by version 0.13.7.
```

When your project contains a lot of expectation suites, it is rather annoying to run `great_expectations suite edit`,  execute the notebooks and save all the expectations again.

Would it be possible for the `great_expectations project upgrade` command to also update the `great_expectations_version`-field of all expectation suites (the .json-files)? At least in situations when there has been no breaking changes (wrt. the format of the .json-files) between the two versions in question.

**Comment by eugmandel** [comment]
@marhoy I updated the title of the issue. This warning is not related to config versioning which great_expectations project upgrade deals with. 
When you create an Expectation Suite, the GE version at the time is recorded within the suite. The warning is displayed if the version of GE that uses this suite is different. The thought there was that an implementation of an Expectation might have changed since, it the suite does not mean exactly same thing. 

The warning did not prove itself to be very useful and should be removed.
