### ISSUE TITLE
Meta argument causes error when used improperly that carries over even when the meta is removed from the expectation.

### ISSUE THREAD

**Issue by James7711** [fivetran/great_expectations#2444]
**Describe the bug**
When you incorrectly use the meta argument in setting up expectations in the jupyter notebook it causes the below error when you run the final step - batch.save_expectation_suite(discard_failed_expectations=False).  This error continues to appear even if you remove the meta argument from all expectations.  In my case I was just passing a normal string into the meta argument.  I have discovered this can be fixed by deleting the files in uncommitted\validations\[suite]\warning\ and re-running through the jupyter notebook.

ValidationError: {'results': {0: {'expectation_config': {'meta': ['Not a valid mapping type.']}}}}

**To Reproduce**
1. create an expectation and only pass in a string to the meta arg, example meat="this expectation does x"
2. run the rest of the code in the jupyter notebook
3. open the edit suite again great_expectations suite edit [mysuite.warning]
4. run through everything again but remove the meta argument entirely

**Expected behavior**
I would expect the error to no longer appear after I run step 4 above 

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.9

**Additional context**
I have discovered a workaround for this bug.  Deleting the files in uncommitted\validations\[suite]\warning\ and re-running through the jupyter notebook.

**Comment by eugmandel** [comment]
@James7711 Thank you for reporting this issue. Reproduced - it is indeed a bug.

**Comment by eugmandel** [comment]
The fact that the error persists even after removing the wrongly formatted "meta" argument from the Expectation is due to the fact that that "meta" was saved in the Validation Result. An ugly workaround would be to find and delete that Validation Result.

We would love for a community contributor to make a PR that catches this error and handles it better.

Beyond that, we believe a longer term fix is to make the "meta" argument adhere to a schema to make it impossible to create a wrong structure.
