### ISSUE TITLE
The `-c` flag to supply a config file is (seemingly) ignored

### ISSUE THREAD

**Issue by olhmr** [fivetran/great_expectations#2570]
**Describe the bug**
Regardless of what value is supplied to the `-c` flag (and whether or not it exists), `great_expectations` runs through the same search pattern to try to find the config file.

**To Reproduce**
1. Run `great_expectations -v suite list`
2. Run `great_expectations -v -c great_expectations.yml suite list`
3. Run `great_expectations -v -c this_file_does_not_exist.yml suite list`
4. Note that all steps above produced identical results.

**Expected behavior**
When a correct config file is supplied, `great_expectations` should not perform a search and instead immediately use that file. If the file does not exist or is invalid, an error should be produced instead.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.14

**Additional context**
Search steps when running 1-3 above locally:

```
> great_expectations -v suite list
Using v2 (Batch Kwargs) API
Searching for config file /.../great_expectations/great_expectations (0 layer deep)
Searching for config file /.../great_expectations (1 layer deep)
Found config file at /.../great_expectations/great_expectations/great_expectations.yml
Using project config: /.../great_expectations/great_expectations/great_expectations.yml
```

```
> great_expectations -v -c great_expectations.yml suite list
Using v2 (Batch Kwargs) API
Searching for config file /.../great_expectations/great_expectations (0 layer deep)
Searching for config file /.../great_expectations (1 layer deep)
Found config file at /.../great_expectations/great_expectations/great_expectations.yml
Using project config: /.../great_expectations/great_expectations/great_expectations.yml
```

```
> great_expectations -v -c this_file_does_not_exist.yml suite list
Using v2 (Batch Kwargs) API
Searching for config file /.../great_expectations/great_expectations (0 layer deep)
Searching for config file /.../great_expectations (1 layer deep)
Found config file at /.../great_expectations/great_expectations/great_expectations.yml
Using project config: /.../great_expectations/great_expectations/great_expectations.yml
```

**Comment by jcampbell** [comment]
Thanks for flagging this -- we're actively working on CLI changes, and I wonder if this may have slipped through the cracks... @alyr: can you take a look?

**Comment by Aylr** [comment]
@olhmr Thanks for the *really clean* write up and find!

We are actively working on the CLI - specifically to help bring v3 API support to the CLI by use of the `--v3-api` flag.

By specifying no flag, the CLI defaults to using the v2 BatchKwargs API. As you correctly demonstrate, the `--config` argument is not supported in the v2 API.

After a discussion about three potential fixes to this problem we have added a fix to our backlog that will detect when a user is using the v2 API and the `--config` flag and raise a helpful error message, rather than the confusing behavior you observed. This message will likely guide users toward v2 API commands that still support the legacy `--directory` arguments. Note that this is not supported in all sub commands, and that inconsistency is what the `--config` flag aims to fix in the upcoming CLI.
