### ISSUE TITLE
BigQuery type 'RECORD' being recognized as 'ARRAY'

### ISSUE THREAD

**Issue by henriquejsfj** [fivetran/great_expectations#2634]
**Describe the bug**
The BigQuery 'RECORD' type is being recognized as 'ARRAY'. Also, a column that is REPEATED is recognized as 'ARRAY'. The problem is that 'ARRAY' seems to not exist in pybigquery. For example, when I do something like:
```python
batch.expect_column_values_to_be_of_type('column', 'ARRAY')
```
I get: `AttributeError: module 'pybigquery.sqlalchemy_bigquery' has no attribute 'ARRAY'`

When I try:
```python
batch.expect_column_values_to_be_of_type('column', 'RECORD')
```
I get:
```json
{
  "success": false,
  "result": {
    "observed_value": "ARRAY"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}
```

**To Reproduce**
1. Create a BigQuery DataSource
2. Try to add expectations as I made in the description

**Expected behavior**
I think the correct would be to have the column that is 'RECORD' recognized as 'RECORD', since that is supported in pybigquery. For the REPEATED columns, I don't know.

**Environment (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Great Expectations Version: 0.13.15
 - Using V2 API

**Comment by eugmandel** [comment]
@henriquejsfj Thank you for reporting this! We will triage and discuss the best way to address this issue. Would you be open to do a PR?

**Comment by Shinnnyshinshin** [comment]
Hi @henriquejsfj so sorry that it took a while to get back to you on this. The cause of the issue is as you described, because `pybigquery.sqlalchemy_bigquery` does not have have `ARRAY` type. 

To be a bit more specific, the `observed_value` in the value comes from the `inspector`, which inspects the BigQuery database we configured. Since BigQuery "knows" what an `ARRAY` is, it will return that as the observed value. 

Now when it comes to the Expectation, it is dependent on the types that are available in the `pybigquery` library. And GE is asking: "is this column of this type the same type as what the inspector returns?".  If the column is of type `ARRAY` then GE is not able to find it in the list types defined in `sqlalchemy_bigquery` and returns an empty list.  And since there is nothing to compare, the Expectation will always return false. 

As things currently stand, there unfortunately isn't much we can do on our end, but the good news is that there is an open PR in the BigQuery repo that adds ARRAY and STRUCT literals, which you can monitor or comment on (I've added a comment as well). 

https://github.com/googleapis/python-bigquery-sqlalchemy/pull/67

Once this feature is added, the Expectation should work as intended. 

If you're ok with it, I'll close this Issue for now. Please feel free to re-open the issue if you run into further problems in the future.
