### ISSUE TITLE
Support for expressing expectation in sql predicate format with Spark Execution Engine.

### ISSUE THREAD

**Issue by richagaur** [fivetran/great_expectations#2927]
My team has lots of expectation defined as sql expression consisting of multiple columns.
e.g: "columnA > 1200 && columnB == 'cod' || columnC == 'prepaid' "

I would like to be able to input sql expression in the form of an expectation which can be defined in the expectation configuration along with the predefined threshold % like mostly.

I tried to implement it using table expectation, but I can't get hold of a row of dataframe in the validation method of metrics. I also tried to use **row_condition**, but that is not supported in spark along with **conditional_parser** requirement which is only Python and Pandas at the moment.

**Comment by talagluck** [comment]
Hi @richagaur - thanks for submitting this issue and apologies for delays! We will discuss internally and get back to you. In the meantime, could you please add some additional explanation/examples for what this would look like in use? How would you specify an ExpectationConfiguration?

**Comment by talagluck** [comment]
Hi @richagaur - just wanted to follow up here. This is a really cool idea that we likely won't be able to prioritize in the near future. Is this something that you might be interested in contributing?

We talked out a couple of ways this might work - it could be something like

`expect_custom_sql_statement_to_evaluate_true` or `expect_custom_sql_condition_true_count_to_be_between`

The domain for the expectation would be the SQL statement (so that we can allow more than one of these within a suite).

You would use a metric_provider (rather than a map_metric_provider) and call the metric something like `rows.match_sql.unexpected_count`.

Let me know if you are interested in contributing, or if I can offer any further assistance!

**Comment by richagaur** [comment]
Hello,

The solution looks good to me. I would happy to contribute for
this project. Looking forward to hearing from you.

Thanks and Regards,
Richa Gaur

**Comment by talagluck** [comment]
Hi @richagaur - thank you so much. That sounds great!

We are currently in the process of migrating our guide on custom expectations to our new docs site. [This legacy page ](https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations.html) might be a good place to get started, though the state of things has progressed since then. Additionally, we are doing in the process of doing some work to make it easier to contribute multi-column expectations. Please take a look, give it a try and let me know what you think, and how I can help!

**Comment by talagluck** [comment]
Hi @richagaur - I'm going to close this issue for now, but we would welcome a contribution at any time! Feel free to re-open this, if it is helpful for you, and otherwise to open a PR when you are ready. Thanks!
