### ISSUE TITLE
_append_expectation should have a keyword argument for which fields to match when overwriting

### ISSUE THREAD

**Issue by edjoesu** [fivetran/great_expectations#297]
Currently append_expectation only supports overwriting based on 'expectation_type' only or 'expectation_type' and 'column' together. 

This requires some kludging for column pair expectations when using the Dataset.expectation decorator, similar for future expectation types where there might be multiple of that type for a column but ['expectation_type', 'column', 'some_parameter'] would be unique together.  

Proposed fix is to add a keyword argument to _append_expectation: overwrite_matching = 'column' that takes a str or list(str) -- I can put it in but wanted to discuss first. 

in dataset/base.py/_append_expectation
```
        if 'column' in expectation_config['kwargs']:
            column = expectation_config['kwargs']['column']

            self._expectations_config.expectations = [f for f in filter(
                lambda exp: (exp['expectation_type'] != expectation_type) or ('column' in exp['kwargs'] and exp['kwargs']['column'] != column),
                self._expectations_config.expectations
            )]
```

**Comment by abegong** [comment]
hm. `append_expectation` should not be doing this check itself. We have a function called `find_expectation_indexes` that takes care of this logic.

I suggest three changes:

1. Refactor `append_expectation` to use `find_expectation_indexes`. (I could have sworn we did this already, but I guess not.)

2. Extend `find_expectation_indexes` to cover the column pair case where `column_A` and `column_B` are the identifying arguments.

3. Extend `append_expectations` in the way @edjoesu suggests, but instead of building the logic within `append_expectations`, use the `kwargs` argument in `find_expectation_indexes`. Within `append_expectations` I vote we call the parameter `matching_expectation_kwargs` to keep the naming consistent with `kwargs` in `find_expectation_indexes`.

**Comment by jpcampb2** [comment]
This is a feature we've talked about a few times, and really is an important (see, e.g. discussion in #277)...and I also thought the refactor of _append_expectation had already happened... 👎 

I agree, @abegong : fixing this by fixing find_expectation_indexes makes sense. 

But we need some thought on a good set of options for how to match. I think, e.g. the column parameter should go away so that all the matching happens based on the requested info. I like the name "match_on_kwargs"

That also means we'd need to provide the right/default values of matching_expectation_kwargs on a per-expectation basis.

So: the new find_expectation_indexes would look something like: `def find_expectation_indexes(expectation_type=None, match_on_kwargs=None)` and if we have a single expectation in our current config:

```
{
   "expectation_type": "expect_column_values_to_be_in_set",
   "kwargs": {
        "column": "a",
        "values_set": [1,2,3],
        "mostly": 0.95
    }
}
```

then 
```
find_expectation_indexes("expect_column_values_to_be_in_set", {"column": "a", "mostly": 0.8}) == []
find_expectation_indexes("expect_column_values_to_be_in_set", {"column": "a", "mostly": 0.95}) == [1]
find_expectation_indexes("expect_column_values_to_be_in_set", {"column": "a"}) == [1]
```

which leaves to _append_expectation to know how to construct `match_on_kwargs` for a given expectation (and the change-nothing logic is that if it's a column-map expectation, it is only the column name).
