### ISSUE TITLE
Pass in arguments for reading in flat files in local filesystem

### ISSUE THREAD

**Issue by ismaildawoodjee** [fivetran/great_expectations#3077]
**Describe the bug**
May I know where and how do I pass in arguments for reading in a flat files stored in filesystem using Pandas' `read_csv`, particularly for the `encoding=<arg>` parameter? This is for the recommended to use Version 3 for new projects, not Version 2.

**To Reproduce**
1. Run `great_expectations --v3-api suite new`
2. Choose `3. Automatically, using a profiler`
3. Choose `1. default_inferred_data_connector_name`. I have already connected to the Datasource
4. Choose a flat file `1. sample_data.csv`
5. Name the Expectations suite `sample_suite`
6. Proceed with yes `Y`
7. See error:
`'utf-8' codec can't decode byte 0xa3 in position 79780: invalid start byte`

**Expected behavior**
A way to specify `read_csv` arguments for Version 3.

**Environment (please complete the following information):**
 - Operating System: Windows 10, Python v3.9.5; Also reproducible on Ubuntu 20.04, Python v3.8.10
 - Great Expectations Version:  0.13.23

**Additional context**
Add any other context about the problem.

**Comment by ismaildawoodjee** [comment]
https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_pandas_dataframe_as_a_batch.html

Instead,
2. Choose `2. Interactively, with a sample batch of data` and open the Jupyter notebook, where 

```
batch_request = {
    'datasource_name': 'sample_name', 
    'data_connector_name': 'default_inferred_data_connector_name', 
    'data_asset_name': 'sample_data.csv', 
    'limit': 1000,
    'batch_spec_passthrough': {
        "reader_method": "read_csv",
        "reader_options": {
            "encoding": "<encoder>"
        }
    }
```

can be specified and passed in through `context.get_validator()`.

Still, choosing automatic profiling gives an error.

**Comment by talagluck** [comment]
Hi @ismaildawoodjee - thanks for your question! I believe this is a bug - when profiling from the CLI, a notebook is automatically generated with the column names from your csv. However, in order to get those column names, Great Expectations needs to take a look at your csv, and since you haven't yet specified the reader options, this will throw an error. We will be reviewing this internally, and will respond in the next week or so to figure out the how soon we can address this.

You should still be able to manually set up a notebook yourself to match the notebook you would get from the CLI, just making sure to pass the reader_options into the BatchRequest as you show above. Please let me know if you have any questions on how to do this.

**Comment by talagluck** [comment]
Actually, it may be possible to pass in a BatchRequest from a .json file from the CLI. You could then specify the reader_options there. Would you mind giving this a shot and letting us know if it works?

**Comment by ismaildawoodjee** [comment]
Hi @talagluck, I tried out what you said on the command line, like this:

`great_expectations --v3-api suite new --batch-request .\batch_request.json`

and it works.

But it doesn't do automatic profiling, even though the `reader_options` are specified. It says:

`Entering interactive mode since you passed the --batch-request flag`

and opens up a Notebook without any Expectations, just like when I chose Option `2. Interactively,...`.

Is there a way to automatically profile and generate Expectations, as per Option `3. Automatically, using a profiler`, while also providing the `--batch-request` JSON file through the command line?

**Comment by talagluck** [comment]
Hi @ismaildawoodjee - you can add a `--profile` flag to profile as well. As a tip, you can type any of the `great_expectations` commands followed by a `--help` to see all of the available options (e.g. `great_expectations suite new --help`). Please let me know if this works for you.

**Comment by talagluck** [comment]
Hi @ismaildawoodjee - apologies for delays! I just wanted to follow up here.

You should be able to specify `reader_options` in your project config under `data_connectors` instead of in your `BatchRequest`, which should enable you to profile without error and without passing a BatchRequest in on the command line.

e.g.
```yaml
data_connectors:
        default_runtime_data_connector_name:
            class_name: RuntimeDataConnector
            batch_identifiers:
                - default_identifier_name
            batch_spec_passthrough:
                reader_method: csv
                reader_options:
                    header: True
                    encoder: <encoding>
```

I'm going to close this issue for now, but please let me know if you have any issues or any follow-up questions. Thanks!
