### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by stvpruitt** [fivetran/great_expectations#309]
HI.

We starting a new data lake based on Spark and HDFS.  A first task is putting a testing framework in place to test our Spark job processing.  A system-under-test would be something like input->job->output, where the testing framework compares expected output from generated input.  This is a simple example and complexity will grow over time.  Plans include to build test automation into our CI system.

I am evaluating frameworks to build the test framework and I ran across great expectations.

My initial impression is great expectations targets more along real-time data testing.  Is this assumption true?  Of course it can be purposed for integration test.

The supported data sources I see are CSV and SQL.  Can the SQL context be used with Spark DataFrames?

Any plans to support HDFS?  Or, is the intent to use other Python libraries?  I guess same can be said true for DataFrames.

Any thoughts, additional questions, or examples would be great appreciated.

Thanks.

-S

**Comment by abegong** [comment]
Good questions.
* This sounds like a great use case for Great Expectations---I'm using it in similar applications.
* Yes, Spark is next up on our list of planned integrations. (See #276)
* On real-time data testing: Great Expectations is agnostic about where it's deployed. We see lots of emerging use cases around production "pipeline testing" because that's usually what's required to fully guarantee data consistency in complex pipelines (see below.) That said, it's also being used for integration tests, within data exploration workflows, as documentation for ML models, etc.

This might be worth a longer conversation. Feel free to reach out to me directly at abegong@gmail.com.

More about pipeline testing: https://medium.com/@expectgreatdata/down-with-pipeline-debt-introducing-great-expectations-862ddc46782a

**Comment by stvpruitt** [comment]
Thanks.  I will get in touch next week.

**Comment by jpcampb2** [comment]
@stvpruitt I'm going to close this issue since you're planning to have this conversation offline, but please feel free to reach out again with other questions (I'm also happy to chat on these issue if you're interested!).

**Comment by gumartinm** [comment]
I wonder how that conversation ended :(

**Comment by abegong** [comment]
What would you like to know?

Great Expectations now has full support for Spark. Are you wondering about HDFS? Real time? Something else?

**Comment by gumartinm** [comment]
Thanks for the fast answer. :heart: 

I was wondering about the capability of comparing expected output from generated input. I do not manage to see datasets implementing it: https://docs.greatexpectations.io/en/latest/reference/glossary_of_expectations.html

Anyhow, I am not sure if in a framework like Great Expectations such capability should exist or perhaps I should think about something different.

**Comment by abegong** [comment]
Can you give an example of the kind of input/output you're looking to compare?

**Comment by gumartinm** [comment]
For example, something like if input has X rows and I know output should always has half of the input rows (X/2) I could validate those values.

But I am not sure if such validation makes any sense at all and perhaps it should be implemented by means of integrations tests or something else. Or not implemented at all.

**Comment by l00173745** [comment]
Hi Guys, wondering about how to connect to HDFS? any hints?
