### ISSUE TITLE
expect_column_values_to_be_in_type_list doesn't match my expectations

### ISSUE THREAD

**Issue by smontanaro** [fivetran/great_expectations#313]
I'm just starting to use ge (0.4.2), and barely know how to use Pandas. Consider this session:

```
>>> import random
>>> dct = {}
>>> for x in "abcde":
...   dct[x] = [random.random() for _ in range(10)]
... 
>>> df = pd.DataFrame(dct)
>>> db = ge.from_pandas(df)
>>> db.expect_column_values_to_be_in_type_list('a', ["float"])
{'success': False, 'result': {'element_count': 10, 'missing_count': 0, 'missing_percent': 0.0, 'unexpected_count': 10, 'unexpected_percent': 1.0, 'unexpected_percent_nonmissing': 1.0, 'partial_unexpected_list': [0.5224400481122169, 0.43833669092251315, 0.1476817687544425, 0.3389329320729022, 0.5478079372396341, 0.5426398330826272, 0.2048097354898295, 0.6208150975480048, 0.37960119902996103, 0.8303684308410247]}}
>>> df['a']
0    0.522440
1    0.438337
2    0.147682
3    0.338933
4    0.547808
5    0.542640
6    0.204810
7    0.620815
8    0.379601
9    0.830368
Name: a, dtype: float64

```

I tried replacing "float" with "float64" and "double", neither of which are understood as strings defining a float. I also tried expect_column_values_to_be_of_type, but that failed in the same way.

I eventually realized that there is another target_datasource, "python", which isn't mentioned in the current documentation for the method. For the sanity of the people writing the bulk of the documentation, I realize you probably don't want to enumerate every possible value of target_datasource everywhere it might be used. It might be nice if one of these options could be implemented though:

* Add a function somewhere in the API which allows users to discover the list of possible target_datasource values, and/or the type names associated with each. Then you only need to refer to that function from the other points. The DataFrame API is already bloated enough (between Pandas bits and GE additions) that maybe this belongs at the top level or in a utils module. Something like

def target_types(source):
    "return a list of type name strings supported for source."
    ...

* Change the result of the failing test to indicate what GE thinks the types of the unexpected values are. (They sure look like floats to me.)

* Given that numpy is the default target_datasource, it's not at all obvious why "float64" isn't a possible type name. I see in pandas_dataset.py that the types are just dicts mapping strings to types. Maybe the numpy target needs a 

    "float64": np.float_

key/value pair

**Comment by jpcampb2** [comment]
@smontanaro I think you're right, and we may just need to drop this until we have a deeper discussion and consideration of how to handle types in great_expectations. We've flagged some problems before, but haven't gotten to the point of actually pulling out the current implementations until there's something better implemented.

@abegong I think I'm ready to pull these out as discussed in #110 until there's a roadmap like what we discussed in #207 Thoughts?

**Comment by abegong** [comment]
I started working on Spark earlier this week and ran headfirst into issues around typing.

It's such a core feature that I'd like to start figuring out how to fix it immediately. Can we make plans tomorrow?

**Comment by jpcampb2** [comment]
That makes sense to me...let's put it as the primary item on the agenda, and we can consider making a rapid PR, including one or more of @smontanaro 's suggestions.

**Comment by ccnobbli** [comment]
To briefly capture some things that are being considered:

1. simple `expect_column_values_to_be_(common_datatype_here)` - mapping of data types for a data context into simpler data types (think `float`, `int`, `string`, etc.)
2. complementary `expect_column_values_to_stored_as`- to capture more granular data types in the storage context, e.g. `numpy.uint8`
3. the most flexible option would be some form of a `expect_column_values_to_be_parsable_with(parsing_function)` - to let the user define a parsing function or to use off-the-shelf parsers to apply to a column. We think this is a good idea because there are plenty of places where people disagree what is "parseable". This would also have the benefit of highlighting values that deviate the norm (e.g. from #110, `exception_list = ["1", "2", "3", "4", "abcd"]` is not useful when checking for `int` parseable values. 

4. (3b) custom parsers could be done via the newly available parameterized expectations #311 (@jpcampb2)

*edit*: grammar

**Comment by abegong** [comment]
Thanks for capturing this discussion, @ccnobbli !

**Comment by smontanaro** [comment]
I'm glad to have sparked (no pun intended) some discussion. I will point out that I think there is a bug which needs fixing which is demonstrated by my original example. If the default target_datasource is "numpy" and I asked it to pass judgement on a numpy array (or a pandas.Series), I would have thought the test would report success. It was only when I explicitly set the target_datasource to "python" that the check succeeded.

**Comment by abegong** [comment]
@smontanaro Yes, that bug is perplexing and clearly needs to be fixed. @jpcampb2 and I are looking into it.

To amplify @ccnobbli 's notes: right now, `expect_column_values_to_be_of_type` conflates two concepts.
1. How is the data actually typed in the current execution engine? (e.g. is it an `np.float64`?)
2. Conceptually, what type of data is this? (e.g. "11" might be typed as a string, but it can be parsed and used as an integer.)

We should disambiguate these two concepts, by separating them out into different expectations.
1. `expect_column_to_be_stored_as_type` Also, possibly: `expect_column_to_be_primary_key`, `expect_column_to_be_foreign_key`. These expectations will be scoped to specific execution environments (e.g. pandas/sqlite/postgresql/SparkDF/etc). They will *not* attempt to map environment specific types (e.g. "VARCHAR(200)) back to generic types (e.g. "string").
2. `expect_column_values_to_be_parseable_as_ints`, `expect_column_values_to_be_parseable_as_floats`, etc. We already have `_as_datetime` and `as_json`. We need to extend the same functionality to more basic types, like ints, floats, bools, etc.

These functions will need to be scoped to specific parsers, which can be overridden by the user.
* For example, GE's out-of-the-box int parser will probably convert "11" -> 11. But it wouldn't know how to convert the roman numerals "mxiii" -> 1013.
* A Roman user could write their own parser with knowledge of roman numerals to accomplish this parsing.
* You could imagine similar parsers for handling edge cases (ex: "" -> 0, "-inf" -> null), or best effort parsing of human-entered values ("seven" -> 7, "2 or 3" -> 2.5, "idk" -> null)

The expectation allows the user to express intent ("Can I use this column as an integer?") and an explicitly declared parser makes that intent concrete and replicable.

**Comment by jpcampb2** [comment]
#323 addresses this issue--thank you for reporting it!
