### ISSUE TITLE
How to detect short rows or truncation?

### ISSUE THREAD

**Issue by smontanaro** [fivetran/great_expectations#321]
I was having trouble with truncation in some input CSV files recently. The files contained legitimate "NA" values, which Pandas mapped to NaN. That seems to be the default "missing" value which it filled in upon reading as well. Is there a succinct test in Great Expectations to check that all records in a CSV file (or its instantiation as a Pandas DataFrame) have (for example) 14 cells?

**Comment by abegong** [comment]
Great question. On one level, this is a pandas issue, not a GE issue. GE's `PandasDataset` builds on top of pandas' `DataFrame` class. We don't intend to replace or override core functionality of pandas methods like `read_csv`.

That said, we've also discussed the idea of expectations applied to raw files, rather than DataFrames that have already been loaded into memory. @dlwhite5 's `expect_file_hash_to_equal` is another example of an "expectation" that would be applied prior to parsing a file.

Some other candidates:
`expect_file_to_be_valid_json`
`expect_file_to_be_valid_xml`
`expect_file_to_be_valid_rfc4180_csv`
`expect_file_size_to_be_between`
`expect_file_to_exist`
`expect_file_last_update_time_to_be_between`
`expect_file_create_time_to_be_between`
...

@smontanaro, I'd name your use case something like
`expect_file_line_column_delimiter_count_to_be_between` or
`expect_file_line_column_delimiter_count_to_equal`

As in:
`expect_file_line_column_delimiter_count_to_equal("my_file_name.csv", delimiter=",", count=14)`

Would that fit the bill?

Related: we'll probably want to distinguish between `*Dataset` nontabular classes and tabular `*DataTable` classes. Unless we can be clever about backwards compatibility, this probably means we'll be introducing breaking API changes.

Thoughts, @jpcampb2 ?

Switching to a new naming convention would be the hardest part of this improvement. Implementing most of the actual expectations should be pretty quick and straightforward.

**Comment by abegong** [comment]
Here's a proposed class inheritance hierarchy:
```
Dataset
  RawFileDataset
  JsonDataset (?)
  XMLDataset (?)
  SparkRDDDataset (?)
  ...
  DataTable
    PandasDataTable
    SQLAlchemyDataTable
    SparkDFDataTable
```

`Dataset` would have the `@expectation` decorator.
`DataTable` would introduce `@column_map_expectation`, `@column_aggregate_expectation`, `@column_pair_map_expectation`, `@column_pair_aggregate_expectation`

Basically, the difference between `Dataset` and `DataTable` is that DataTable is tabular and therefore has the concepts of rows and columns.

**Comment by jcampbell** [comment]
This now can be accomplished. Note that we ended up using a different structure than originally proposed:

DataAsset
   FileDataAsset
   Dataset
      PandasDataset
      SQlAlchemyDataset
      (SparkDFDatset)

The primary reason was ensuring that existing code using dataset naming would not be affected.
