### ISSUE TITLE
Stacking Expectations of same type (coming from the same `expect_` method)

### ISSUE THREAD

**Issue by AntonBiryukovUofC** [fivetran/great_expectations#3300]
**Is your feature request related to a problem? Please describe.**

I have a custom expectation (column map one) that calculates a ratio between a quantile for the whole dataset and quantile in a rolling window. What I would want from the expectation suite is to check whether that ratio is within a certain interval for multiple quantile levels. If i add multiple expectations for each quantile via `validator.expect_*_ `, then after export, json has only one expectation (the last quantile). However, I would love to keep both of those expectations.

**Describe the solution you'd like**

Two (or more) expectations acting on 2 (or more) quantile levels independent of each other persisted in JSON and validator object.

Same should apply for default expectations if they were to be "stacked".

**Describe alternatives you've considered**

I can also just re-work my custom expectation to accept a list of quantiles, and a list of interval tuples, similar to how quantile values expectation is done. But then that has to be done with all the other default expectations as well if they were to be "stacked". So not really an alternative, but a custom hack rather.

**Additional context**
None

**Comment by talagluck** [comment]
Hi @AntonBiryukovUofC - thank you for bringing this up. Currently, it is not possible for an Expectation Suite to have more than one `ExpectationConfiguration` with the same `expectation_type` and the same `domain`. This is something that we've talked about periodically, but I don't believe we have any plans to change this in the immediate future.

I appreciate the use case you've presented here for this particular custom expectation, and recognize that that wouldn't quite work in this case. Your intuition to format this similar to the quantile values expectation make sense. For most expectations, if a user would like multiple "levels" of strictness, we would recommend splitting those `ExpectationConfigurations` up into multiple suites.

I will bring this up internally in the next few days to confirm that this is the latest state on having multiple expectations with the same `expectation_type` and same `domain` within one Expectation Suite.

**Comment by talagluck** [comment]
Hi @AntonBiryukovUofC - I wanted to follow up here. Since you are working with a custom expectation in this case, it should be possible to achieve what you are seeking if you modify the `domain_keys` tuple in your expectation to include your `quantiles` key. When adding an `ExpectationConfiguration` to an `ExpectationSuite`, we check for equivalency by comparing the `domain` and `expectation_type` to the existing `ExpectationConfigurations` in the Suite. Modifying the `domain_keys` tuple here should cause the `ExpectationConfiguration` to evaluate as different from existing `ExpectationConfigurations`, and thus not overwrite. [You can see an example of `domain_keys` here.](https://github.com/great-expectations/great_expectations/blob/f236bbad829a8fcdc56a3cbd61d4f80b2a13b51c/great_expectations/expectations/core/expect_column_to_exist.py#L63).

Please let me know if this works for you, or if you have any follow-up questions.

**Comment by talagluck** [comment]
I'm going to close this for now, as I believe it is resolved. If you have any further questions please don't hesitate to reach back out!
