### ISSUE TITLE
GreatExpectations config object should allow for namespace to expectations

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#345]
When a user creates subclasses of a Dataset and implements custom expectations, those expectations become available to be included in a config object. However, the config does not specify the class that was used to generate it or provide other mechanisms to specify which "my_custom_expectation" should be evaluated.

I don't think that's in general a big problem, but it does seem like it would be nice to do something as basic as providing a name for the class from which a config was obtained as part of the config's meta object.

**Comment by abegong** [comment]
Makes sense. Seems like a worthwhile power user feature.

**Comment by ccnobbli** [comment]
What would be an example of this? Asking for a friend.

**Comment by jpcampb2** [comment]
Suppose you've got a project working with bilingual translation data, and a custom expectation related to the length of segments in your data, along the lines of `expect_column_word_length_to_be`. That is implemented by:

```
class TranslationDataset(PandasDataset):
    
    def expect_column_word_length_to_be(...)
        ...
```

If someone gets that config, they'll observe you had an expectation called expect_column_word_length_to_be, but not know where that came from...we should also ensure that TranslationDataset is there.

This is really about looking forward to the ability to name sets of parameterized expectations, but I think the simpler fix is a starting point.

**Comment by jcampbell** [comment]
See PR #439 that addresses this via data_asset_type

**Comment by abegong** [comment]
From PR #439:

> This clarifies which extra expectation logic is needed to evaluate that expectation config, since previously that has been entirely implicit."

This implicit-ness is the heart of the matter, IMO. Putting some thoughts on paper to fuel discussion.

AFAICS, there are three potential use cases for subclasses of DataAsset:
1. execute Expectations against new compute engines (pandas vs SQL vs Spark vs ...)
2. extend the Expectation DSL with additional Expectations
3. override the business logic for existing Expectations

This raises two major potential problems.

First, conflict between "1 good / 3 bad".

(1) seems awesome: evaluate the same Expectations in multiple contexts and get consistent results.

We strongly discourage (3), since it destroys the notion that Expectations have consistent meaning across contexts.

But actually, variable types make things complicated very quickly, since they conflate (1) and (3), both for explicit type-checking Expectations, and for Expectations where types affect the logic of Expectations (e.g. `parse_datetimes_as_strings`, or "2" > "10" but 2 < 10.)

We need to have a good answer to this question: **What guarantees does Great Expectations make about consistency of Expectation results in different execution contexts?**

Example: If I have a
* (1) table in PostgreSQL
* and I download it as (2) a CSV,
* then load it into (3) a Redshift table,
* and then run Expectations against (1), (2), and (3)...

Should I get consistent results?
If not, which results could be different?
What will the differences depend on?

Second, (2) raises an "orphan Expectation" problem. In your words:

> The config does not specify the class that was used to generate it or provide other mechanisms to specify which "my_custom_expectation" should be evaluated.

Your proposed solution above partially fixes this: store the provenance of Expectation suites. "This suite was generated by class X (from GE version Y, git hash Z)." This is pretty close to a guarantee that we'll be able to validate the Expectations again using that class.

But it raises a 2nd order problem: as we start slicing and dicing configs with power tools, there's no guarantee that any config will be generated by a single class at a single point in time.
* We could push provenance down to the level of individual Expectations, but that still begs the question which class should be used to execute Expectations.
* Conceivably, we could use multiple classes for execution, but that seems very unwieldy.
* Also, it doesn't answer a prior question: when slicing and dicing, which Expectations can be sensibly co-mingled. For example, it doesn't make any sense to mix FileAsset Expectations referring to directory structures with Dataset Expectations that refer to columns.

I think we're going to need to be opinionated about these issues, and make those opinions explicit in docs:
* Which Expectations can be sensibly co-mingled?
* What guarantees does Great Expectations make about consistency of Expectation results in different execution contexts?

**Comment by jcampbell** [comment]
I think there's a fourth critical use case for subclassing DataAsset, which comes from the fact that the second "extending the expectation DSL" really covers two fairly different kinds of extensions.
1. extending the expectation DSL with additional expectations, vs.
2. extending the expectation DSL with additional domains

The first is what has been available with custom expectations--they're fundamentally of the same type and logically coexist with other expectations in a given domain (tabular data in the case of the Dataset object).

The second is what just happened with FileDataAssets -- it doesn't make sense to think of an expectation about a file hash coexisting with an expectation about a column's distribution: they're operating on different layers of abstraction.

---

I agree that the tension between "1 good / 3 bad" is fundamental. This might be the only time I say this...I wish python had an equivalent to Java's `final`. But I think that's also a situation where if someone chooses to subclass, they went into it eyes open; you have to trust the GE compute engine against which you're validating an expectation config. As for the type issues...we've had these discussions since the beginning, and I think there's probably the makings of a religious war in there somewhere. ;)

I think our *goal* should be to strive for "semantic identity" across compute platforms, but I think we've also embraced a philosophy of (hopefully temporary) computational inefficiency in the sense that we advocate using multiple expectations bagged together to get the overall semantic goal. So, you might combine your `expect_column_values_to_be_between` with an `expect_column_values_to_be_of_type` to get the overall semantic meaning you want in the 2, 10 example.

I'm hesitant to embrace a guarantee on that though...and I think that's okay, because it's necessary when some things are out of your control (we're trading that guarantee for the cross-platform consistency).

---

Last direction of questions here makes a lot of sense to me. The current approach is that "Dataset" expectations can be co-mingled, and "FileDataAsset" can be. I think a really useful approach would be to keep it at that level of abstraction--for "core" GE types, we provide a managed experience. For custom ones, we provide cues to manage (namely the config-level attribute of data_asset_type).

Finally: concretely with respect to slicing and dicing--the current structure lends itself well to those operations, but when it comes to *splicing* we basically leave that to the reader. That is, if you want to validate different objects using the same config or use different configs on the same object, those are both out-of-band operations, whereas we could instead do something slightly different like:

```
{
configs:[
{
  ...
  data_asset_type
  expectations: []
},
{
  ...
  data_asset_type
  expectations: []
]
}
```
to give a clue to the validator to know to use different implementing classes on a given object for different subsets of expectations. (Incidentally, I've toyed around with that a bit in terms of thinking about how to best structure different levels of alerts)
