### ISSUE TITLE
Expectations on full row, each group in Groupby, or full DataFrame?

### ISSUE THREAD

**Issue by shippy** [fivetran/great_expectations#351]
I'm thinking about expectations that operate on larger substructures than a column or a column pair. Inspired by the discussion in #236, especially the proposed `@multicolumn_map_expectation`, I wonder how difficult you think it might be to implement `@row_map_expectation`, `@groupby_map_expectation`, or `@dataframe_map_expectation`? Do you think that's within the possible scope of the package?

Some use cases that lead me to think about this:

1. `@row_map_expectation`: If a particular column is null, then I expect all other columns to be null. 
    (Current workaround: use #255 `util.create_multiple_expectations` in combination with some custom expectation built on `@column_pair_map_expectation`, then sort through the flotsam to find row indices for which this wasn't true in at least one of these expectations?)
2. `@groupby_map_expectation`: A longitudinal / time-series DataFrame grouped by primary key, in which I want to test ~~that dates are monotonically increasing and separated by at least 120 days~~ that each event identifier is unique within group. 
    ~~(Current workaround: For this particular one, it is easy to transform into a single-column check, I guess - lag the original column, compute `original - lag` in a new column, expect that `original - lag > pandas.Timedelta(120)`.)~~
3. `@dataframe_map_expectation`: Do all numerical columns form an invertible matrix?

**Comment by abegong** [comment]
These are great suggestions!

A few thoughts on specifics:
1. `@row_map_expectation` is nice. Can you suggest names for a few specific expectations of this type?
2. We've avoided including transformations (including group-bys) in expectations, because the surface area of possible transformations is enormous. This might be a good avenue for implementing something along these lines: https://github.com/great-expectations/great_expectations/issues/294
3. `expect_dataframe_to_be_invertible` is a cool idea. It should be implementable as pure `@expectation`: by default, this covers a whole dataframe.

**Comment by shippy** [comment]
Thank you for your response!

1. I'll admit I'm really in it for the decorators that would allow me write my own dataset-specific expectations :) For generalizable row expectations, all I can think of is `expect_row_to_have_n_notnull_values(column_name, n)` + `expect_row_to_have_at_least_n_notnull_values(column_name, n)` (and the `n_null_values` inversions)...
2. I'm not sure I'm following -- can't the preprocessing / transformation take place entirely outside of GE, and GE would just be handling the group-by's as one more data structure type? (I might not be seeing the whole picture -- I guess this might disable a class of expectations for CLI validation, and maybe other contexts implement grouping differently?)
3. Awesome! I'll look into that.
