### ISSUE TITLE
Feature Request: Infer Expectations from Dataset

### ISSUE THREAD

**Issue by krlng** [fivetran/great_expectations#366]
I really like your approach on how to test data. How ever I find it rather cumbersome to write down many trivial expectations for a larger dataset. I thought it might also be possible to infer or learn those expectations from a correct dataset, store them to apply them on a different dataset later. I also might create a pull request therefore if there is interest in something like this?

**Comment by abegong** [comment]
This would be fantastic.

Note: this issue is related to #362 . You can think of inferring column name expectations as a very basic form of expectation inference.

Having the option to choose among `inference=None`, `inference=columns_only`,  `inference=columns_and_types`, `inference=something_awesome`, etc. would be amazing.

**Comment by jpcampb2** [comment]
@krlng -- Please do consider adding a new autoinspect_func to the new autoinspect.py module...the only one there now simply replicates the old behavior (and now removed) behavior of adding expect_column_to_exist expectations.

Would you like to leave this issue open to discuss more specifics of what the behavior ought to be?

**Comment by jcampbell** [comment]
We'll continue to track improvements to autoinspect as a useful feature, and internally have been doing some thinking on how best to present this to users and update them, but I'm going to close this issue for now until we are ready to prioritize it.
