### ISSUE TITLE
Error: No great_expectations directory was found here!

### ISSUE THREAD

**Issue by ashishtele** [fivetran/great_expectations#3677]
**Describe the bug**
Hey Team, 
I am getting an error at:
context = ge.data_context.DataContext()

Tried with a stable version as well, but the error persists

**Environment**
 - Operating System: [ Windows]
 - Great Expectations Version: [0.13.8]

**Additional context**

![image](https://user-images.githubusercontent.com/14126898/141707721-89b6cd1f-4f51-4364-bf79-9a270a769d22.png)

**Comment by talagluck** [comment]
Hi @ashishtele, can you please run `ls` in the directory where you are running your script? If you have run `great_expectations init` and have a `great_expectations` directory in this location, you will not see this error.

Alternatively, if you would like your script to be in a different location, you can pass in the directory of your Great Expectations argument as below:

```python
context_root_dir = "link/to/my/project/dir/great_expecations"
context = ge.data_context.DataContext(context_root_dir=context_root_dir)
```

**Comment by ashishtele** [comment]
Hi @talagluck , Thank you for helping here. After having **great_expectations** directory at root location, when I run command:

context = ge.data_context.DataContext()

I am getting the below Error:

> great_expectations.exceptions.exceptions.InvalidConfigError: Your current configuration uses the "generators" key in a datasource, but in version 0.10 of GE that key is renamed to "batch_kwargs_generators". Please update your configuration to continue.

**Comment by talagluck** [comment]
Hi @ashishtele - it appears that you are using a very old configuration. I would recommend that you go through our [Getting Started Tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/intro), as this will provide you with the tools you need to set up a project, and to be able to ask questions in our [community Slack](https://greatexpectationstalk.slack.com/join/shared_invite/zt-sugx45gn-SFe_ucDBbfi0FZC0mRNm_A#/shared-invite/email).

Since this issue is focused on configuration rather than a bug, I'll close it for now, but don't hesitate to reach out if you have any questions after completing the Getting Started Tutorial.
