### ISSUE TITLE
capture unexpected _index_list for pyspark dataframe

### ISSUE THREAD

**Issue by sdandey** [fivetran/great_expectations#3716]
Hi,

I'm a newbie and working on ge with pyspark engine.  I'm evaluating this product for our possible data-quality checks adoption.  One of our requirement for our product is to capture/tag data with meta-data that has failed the expectations.  The similar functionality can be achieved used the unexpected_index_list.

When I tried running the following code the results for unexpected_index_list it returns null object.  My questions

1. How can we create Index for the pyspark df.  
2. For my expectation expect_column_values_to_not_be_null, it returns the null value as an array which doesn't provide me enough information for debugging. 
3. How can we update the original spark dataframe with additional meta-tags capturing all the error expectations within the dataframe? 

Here is the sample result I get when I run.   
df_ge.validate(result_format='COMPLETE')

{
      "result": {
        "element_count": 479,
        "unexpected_count": 4,
        "unexpected_percent": 0.8350730688935281,
        "unexpected_percent_total": 0.8350730688935281,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_index_list": null,
        "unexpected_list": [
          null,
          null,
          null,
          null
        ],
        "unexpected_index_list": null
      },
      "exception_info": {
        "raised_exception": false,
        "exception_message": null,
        "exception_traceback": null
      },
      "meta": {},
      "success": false,
      "expectation_config": {
        "kwargs": {
          "column": "Type",
          "result_format": "COMPLETE"
        },
        "expectation_type": "expect_column_values_to_not_be_null",
        "meta": "Missing Type",
        "ge_cloud_id": null
      }
    },

**Comment by cwerner** [comment]
I think I have the same problem using a PostgreSQL table as a data source. I plan on identifying individual data rows that trigger an exception for QC but currently I'm always returned `null` for `unexpected_index_list` which currently is a total showstopper for my use case. 
Same for the `partial_unexpected_index_list` though I don't need that one. I do see values in the `partial_unexpected_list` field but I don't need those...

This worked for me in a previous project (way back) for pandas dataframes so not sure if this is related to the data source or a GE regression? 

Also, is this the most efficient way to identify data rows that fail? I'll process _A LOT_ of data if this approach works out...

I'm on 0.13.43

**Comment by sdandey** [comment]
I would prefer an approach of appending data quality tags on original data frame or spit the bad records into a different location. This would provide more to the point debugging for our product users to correct and re-upload the data

**Comment by alitsaberi** [comment]
Hi everyone,
I have the same issue. I want to separate unexpected row from valid data. It seems that GE return a null `unexpected_index_list` for Spark dataframes. One possible workaround is to use `unexpected_rows` as it return the rows themselves. But there is no easy way to eliminate these rows from original dataframe and for large dataframes, this could return an unwieldy amount of data.

**Comment by talagluck** [comment]
Hi @sdandey and @cwerner! @alit8 is right here. `unexpected_index_list` currently only works the `pandas` back-end.

Unfortunately, we don't have a built in way to handle this currently -- although it is a feature that is being looked into (you can reference [this issue](https://github.com/great-expectations/great_expectations/issues/3195) for more information on that).
There are currently three ways of doing what you want, although none of them are perfectly ideal:
1. Using the returned unexpected_values metric in your ValidationResult (you will need to use result_format="COMPLETE") to query your data (in your own environment) and return the complete rows that have failed.
2. Using the include_unexpected_rows flag in result_format to return the entirety of each row that has failed an expectation ([see here](https://docs.greatexpectations.io/docs/reference/expectations/result_format)). This has the potential to return huge amounts of data within your ValidationResults, so I would advise caution when using this.
3. Pass your data to a pandas DataFrame, which will enable you to get unexpected_index_list with a “COMPLETE” result_format.

I'm going to close this for now, since I believe the functionality that this is seeking is a duplicate of #3195. Thank you for the feedback!
