### ISSUE TITLE
expect_file_to_be_pandas_parseable

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#375]
In the spirit of #321 and #110:

```
my_filehandle.expect_file_to_be_pandas_parseable(
  pandas_method="read_table",
  pandas_kwargs={
    "sep" : "|",
    "header" : 2,
  }
)
```

Thoughts, @jpcampb2 ?

**Comment by jcampbell** [comment]
The discussion in #378 landed on what became `expect_file_line_regex_match_count_to_equal`... but I think the intent here was a bit cleaner (because it explicitly handles escaping and delimeters via the pandas parser). I'm inclined to think we should add this as a new expectation now that that framework is in place... (after a long delay, @abegong )

**Comment by abegong** [comment]
Agreed. I'm increasing bullish on `expect_*_to_be_*_parseable`-type Expectations.
