### ISSUE TITLE
How do I update out of date configs?

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#376]
When a new release of great expectations comes out, we currently warn if your config was built using a previous version, but there isn't an automatic upgrade path.

Usually (so far), there's no problem--you could literally replace the verison numbers and be okay between most 0.x.y changes in y-value, but we should clarify that.

Note that looking for changes in our test suite's expected results is usually a really good indication of whether you need to change the config itself (vs. just changing the version number). But we should also add information into the changelog.

<this is a placeholder issue for better documentation about this migration path>

**Comment by smontanaro** [comment]
I just hit this in the upgrade from 0.4.4 to 0.4.5. It's nice to know that y+1 shouldn't normally cause a problem. It would be kind of nice if there was a way to run the g_e cli tool to validate and (possibly) regenerate the config.

**Comment by jcampbell** [comment]
I agree it would be nice to have a specific path for updating configs based on changes in, say, expectation names, and opened this issue as a placeholder for that kind of idea. So far, we haven't had that level of breaking change in config...in your upgrade did you find an (unexpected) change was required in the config, or did you just observe the warning?

**Comment by smontanaro** [comment]
Just observed the warnings and preferred to get rid of them (spurious noise
in this case).

**Comment by jcampbell** [comment]
Got it; thanks for confirming. We've updated the warning message a bit to give you both versions so you can see the point/non-point release difference. At this point, consulting the changelog is the best route to being 100% confident about behavior (but of course we also recommend running the same config on available test data as well). I'm going to close this for now since we do not plan to develop a migration tool in the near future.
