### ISSUE TITLE
MS Teams webhook instead of Slack?

### ISSUE THREAD

**Issue by santoshg117** [fivetran/great_expectations#3883]
**Describe the solution you'd like**
Is it possible to somehow use a MS Teams webhook rather than slack? When I try to use a teams webhook by default, it doesn't pass validation and the following message is displayed:

ValueError: Please provide a valid slack webhook

**Comment by derek-hk** [comment]
Definitely possible! Your error message tells that u have used a **slack** classes/modules to do **teams** notification, which is impossible!
Basically three steps is involved.
1. Configure a "incoming webhook" application in a teams channel.
https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/how-to-configure-and-use-incoming-webhooks-in-microsoft-teams/ba-p/2051118
2. Place the link generated in (1) into great expectations' conifg_variable.yml (It normally be stored in \uncommitted folder)
![image](https://user-images.githubusercontent.com/90680179/146881630-3e4d908c-7c02-431b-8c24-aa2e16a6f33c.png)
3. Add a teams notification process in your checkpoint yaml file, where ${teams_webhook} = what u have created in (2), make sure that you have used classes for Teams instead of slack
![image](https://user-images.githubusercontent.com/90680179/146881953-b32caa38-d3f9-42b9-8c1a-d57f7151c83b.png)

After these, your checkpoint shd be able to push notification to the teams channel

**Comment by talagluck** [comment]
@derek-hk has the answer (thanks for jumping in)! I'm going to close this for now.
