### ISSUE TITLE
In V3 while creating a new suite with athena creates two temp table one at suite creating time and other one while running checkpoint

### ISSUE THREAD

**Issue by sushrut9898** [fivetran/great_expectations#4028]
When we create and save a new suite in the V3 via notebook with Athena, two temp tables are created.
One when we create the suite or define data_asset and another one when we try to run all expectations (run validations) using checkpoints. Is there any way we could reuse the temp table while creating the suite for running validations just like we did with v2? 

1. setup GE for v3
2. Configure data source to connect to Athena.
`datasources:
  my_athena:
    module_name: great_expectations.datasource
    execution_engine:
      connection_string: awsathena+rest://:@athena.us-east-1.amazonaws.com:445/default?work_group=primary
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
      default_configured_data_connector_name:
        class_name: ConfiguredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector`
3. Create a new suite with "great-expectations suite new "
4. use the notebook to specify the data asset and add expectations to a suite (First temp table ios create d at this point.)
5. run the save ad review your expectations (second temp table created by checkpoint here)

Is there any way we could reuse the temp table created while creating the suite or the validator object again in the checkpoint instead of creating a new one? 

 - Operating System: windows
 - Great Expectations Version: 0.14.0

**Comment by AFineDayFor** [comment]
Thank you for bringing this up @sushrut9898. The team will talk it over and get back to you.

**Comment by Shinnnyshinshin** [comment]
Hi @sushrut9898 thank you for bringing this up.  The issue seems to be rising from GE creating a permanent table whenever we create an `SqlAlchemyBatchData` object, which happens whenever we create a `Batch` from `BatchSpec`. This means a new permanent table is created anytime we create a `Validator`, and also anytime we run a `Checkpoint` (which can result in many many tables)

We've created a PR that sets the default behavior of GE to **not** create a permanent table during this step, which you can track at #4103 . Once it is accepted and merged, it should be part of an upcoming GE release. 

Until then, here is a workaround that you will be able to use the following workaround whenever you are using `batch_request`, setting the `create_temp_table` value to `False` at the `batch_spec_passthrough`-level. 

```python
batch_request = {
    "datasource_name": "my_datasource",
    "data_connector_name": "default_inferred_data_connector_name",
    "data_asset_name": "taxi_data_database.taxitable",
    "limit": 1000,
    "batch_spec_passthrough":{
        "create_temp_table": False 
    }
}

```

Please let us know whether this workaround works for the time being, and we will also update you regarding the status of the PR and subsequent release.

**Comment by namanchawla** [comment]
Hello @Shinnnyshinshin thank you, the above suggested workaround works.

**Comment by Shinnnyshinshin** [comment]
@namanchawla the latest release of GE `https://pypi.org/project/great-expectations/0.14.6/` now includes the change where the default behavior of GE to not create a permanent table for `awsathena`.  Glad to hear the workaround works for you, and glad to share that you wont have to do it going forward :)
