### ISSUE TITLE
`expect_kl_divergence_of_column_A_and_column_B_to_be_between`

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#403]
Within pairwise expectations, it'd be great to have a simple way to assert that two columns have similar distributions...

Also, as we start building cross-table expectations, a similar thing would be very useful.

**Comment by anhollis** [comment]
I agree that this would be very useful, and probably not terribly difficult to implement. I might take a crack at creating a PR for this.

**Comment by anhollis** [comment]
An expectation for the KL divergence of a pair of columns does not really fit neatly under the paired expectation framework (as we aren't really interested in row by row paired comparisons) or the aggregate expectation framework (as we are dealing with two columns).  This function would be an example of a paired aggregate expectation. Is it worth implementing a framework/decorator for this kind of expectation at this point or should we just create `expect_kl_divergence_of_column_A_and_column_B_to_be_between` as its own stand-alone expectation?

**Comment by jpcampb2** [comment]
Paired aggregates... :)

It'd be useful for me to anchor my thinking in some dataset that we'd want to make this expectation on...I think I usually think of datasets where we often hope for distinct distributions rather than overlapping ones.

**Comment by anhollis** [comment]
I think of this tool as being a good way to check our expectations about the similarity of two variable distributions as Abe mentioned. One real world dataset where this might be useful is the American Community Survey. One thing we could look at with this data is household income and home value. Typically, income and home value follow right skewed distributions with a similar shape, so we might expect there to be a relatively small KL divergence between these variables. 

In some cases, finding that two variables have similar distributions may indicate some interesting relationships between those variables. For instance, one reason home value and income are distributed similarly is because they are both indicators of wealth. This might be a useful discovery if the user was interested in running a regression and wanted to avoiding using variables with redundant information (which might lead to multicollinearity).
