### ISSUE TITLE
Set membership

### ISSUE THREAD

**Issue by RoyalTS** [fivetran/great_expectations#447]
There are actually three types of set membership I may want to test. I may want to test that the set of distinct values in a column

1. is contained in a reference set
2. equals a reference set
3. contains a reference set

`expect_column_values_to_be_in_set()` covers (1). Would you be interested in having expectations for (2) and (3)? If so, is the best way to do this to add additional expectations? Or to define a new one that distinguishes between the three cases using an argument?

**Comment by jcampbell** [comment]
I think this makes a lot of sense and that it would be best implemented as part of a new expectation. Mostly because I think (2) and (3) are actually aggregates, whereas (1) is a map expectation.

Also flagging #412 because that issue contains current discussion about clarifying the working `expect_column_values_to_be_in_set`

**Comment by jcampbell** [comment]
(I suppose to be more precise, it's not that (1) *has* to be a map expectation, but it currently is implemented that way so that it can give row-wise unexpected values).

A bit like how `expect_column_values_to_be_unique` is a map expectation but `expect_column_unique_value_count_to_be_between` is an aggregate.

**Comment by RoyalTS** [comment]
Makes sense.

Got any name preferences? `expect_column_to_contain_at_least()`/`at_most()`/`exactly()`?

**Comment by jcampbell** [comment]
What about:
(2) = expect_column_distinct_values_to_equal_set
(3) = expect_column_distinct_values_to_contain_set

(and (1) isn't added as a different expectation right now)

**Comment by abegong** [comment]
These names lgtm

**Comment by jcampbell** [comment]
This turned out to be a prescient issue for profiling, where in general we want to use aggregate expectations for which an observed_value makes sense; in that context, it's more useful to be able to express set membership as an aggregate, so I've also added `expect_column_distinct_values_to_be_in_set` in a forthcoming PR.

**Comment by RoyalTS** [comment]
Haha! I had that fully coded up only to kick it out again :)

**Comment by jcampbell** [comment]
Sorry!! Thanks for getting these going in the first place. Fortunately, the implementation is just a direct analogy of the others, so hopefully it didn't feel like much wasted work. ;)

**Comment by RoyalTS** [comment]
Not at all. Glad the implementation was easy to re-use!
