### ISSUE TITLE
Markdown files on GitHub have broken links to code snippets

### ISSUE THREAD

**Issue by andyjessen** [fivetran/great_expectations#4579]
**Describe the bug**
Markdown files on GitHub have broken links to code snippets. 

**To Reproduce**
1. Search for "python file=" within code.
2. Select sample (docs/guides/connecting_to_your_data/filesystem/pandas.md) file.
3. See missing content.

![Relative Links Missing](https://user-images.githubusercontent.com/62343929/160506012-bbeb3ec1-f04d-4091-8bc1-0213aa1f0c20.jpg)

**Expected behavior**
Expect relative path to be rendered in GitHub. Alternative approach is to replace the link with code snippet.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: [e.g. 0.13.2]

**Additional context**

**Comment by talagluck** [comment]
Hi @andyjessen - thanks for raising this! We use Docusaurus, which link to external code snippets which are under test. As such, you'll only be able to read the fully rendered version of these on our docs site - the rendering won't be possible when viewing on Github.

I'm going to close this for now, since I don't think there is a viable solution, but if you have any suggestions, please feel free to re-open!
