### ISSUE TITLE
SQLAlchemy warning when not using SQL

### ISSUE THREAD

**Issue by alexszym** [fivetran/great_expectations#5058]
**Describe the bug**
I'm using Azure Blob Storage as a backend and getting the following warning in the new version of ge 0.15.4. Don't think this warning showed up in versions prior to 0.15.

`WARNING:great_expectations.data_context.util:Something went wrong when trying to use SQLAlchemy to obfuscate URL: Could not parse rfc1738 URL from string 'BlobEndpoint=xxxxxx'`

**Expected behavior**
No warning of this is type should show when TupleAzureBlobStoreBackend backend is used.

**Environment (please complete the following information):**
 - System: Azure
 - Great Expectations Version: 0.15.4

**Comment by LeRouxVisser** [comment]
Im getting the same error when using TupleAzureBlobStoreBackend

**Comment by zrluety** [comment]
I am getting the same error. I've included my data source config below

```python
datasources={
        "pandas": DatasourceConfig(
            class_name="Datasource",
            execution_engine={
                "class_name": "PandasExecutionEngine"
            },
            data_connectors={
                "azure_data_configured": {
                    "class_name": "ConfiguredAssetAzureDataConnector",
                    "container": "\\$web",
                    "assets": {
                        "blob_csv": {
                            "pattern" : r".csv$",
                    }},
                    "azure_options": {
                        "conn_str": "DefaultEndpointsProtocol=https;AccountName=<ACCOUNT>;AccountKey<KEY>;EndpointSuffix=core.windows.net",
                    }
                }
            },
        )
    },
```

**Comment by dvanbrug** [comment]
This looks like it's the result of an attempt to sanitize the `connection_string`, which is one of the `cls.URL_KEYS`, here:

https://github.com/great-expectations/great_expectations/blob/bd29694677eb83d2461a3b13ea07b060b14b2ed7/great_expectations/data_context/util.py#L601-L614

In the same way that sqlite urls are skipped, perhaps Azure connection strings should be skipped as well?  

https://github.com/great-expectations/great_expectations/blob/bd29694677eb83d2461a3b13ea07b060b14b2ed7/great_expectations/data_context/util.py#L569-L571

Else custom logic might be needed to mask them instead of treating them like a URL.

**Comment by dvanbrug** [comment]
I was able to add the following snippet as a workaround right after the sqlite check in `_mask_db_url_no_sa` for now.  

```python
# Parse Azure Connection Strings in a special way
azure_conn_str_re = re.compile("(DefaultEndpointsProtocol=(http|https));(AccountName=([a-zA-Z0-9]+));(AccountKey=)([a-zA-Z0-9=\+]+);(EndpointSuffix=([a-zA-Z\.]+))")
if azure_conn_str_re.match(url):
    m = azure_conn_str_re.match(url)
    return f"DefaultEndpointsProtocol={m.group(2)};AccountName={m.group(4)};AccountKey=***;EndpointSuffix={m.group(7)}"
```

It's not very elegant in that it still results in warnings from the initial SQLAlchemy parsing attempt.  One underlying issue is that it would seem other DB (e.g. BigQuery) usage of `connection_string` indeed use URLs, however Azure's is not a valid URL as the original error states.

**Comment by mereldawu** [comment]
Have the same problem - any ETA on this?

**Comment by pfuerste** [comment]
Same for me, my credentials are being written to the logs.

**Comment by mmceng** [comment]
This issue still occurs in great expectations 0.15.41

**Comment by mingyyy** [comment]
I am having the same issue. Could someone provide some ideas? Thank you!

**Comment by mateoxc** [comment]
Hey @mingyyy,
I described the solution here #6139

**Comment by austiezr** [comment]
Hey folks, thanks for your context & patience here. Core team is taking this on ASAP. Look for updates here very soon. 🚀

**Comment by mingyyy** [comment]
Hey @mateoxc, thank you for your reply. Really appreciate it. 
```stores:
expectations_AZ_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleAzureBlobStoreBackend
      container: <blob-container>
      prefix: expectations
      connection_string: ${AZURE_STORAGE_CONNECTION_STRING}
```
This is exactly what I am using to design my DataContextConfig which created the above mentioned SQL error.

**Comment by mmceng** [comment]
Hey @mingyy,
I confused the threads, this issue still occurs

**Comment by pfuerste** [comment]
I am still having this Issue under 0.15.48.

**Comment by mingyyy** [comment]
@pfuerste 0.15.48 doesn't include this merge I think
