### ISSUE TITLE
Merge zip-related expectations

### ISSUE THREAD

**Issue by sp1thas** [fivetran/great_expectations#5414]
**Is your feature request related to a problem? Please describe.**
There is a different expectation for each US state and I think this is a bit inefficient. There is a lot of code duplication because only the state abbreviation changes on each expectation. I propose to merge all these expectations into a single one and allow the user to pass extra optional arguments supported by `zipcodes.filter_by` I.e: `city`, `state`, `country`, `lat`, `lon` etc.

**Describe the solution you'd like**
Merge `expect_column_values_to_be_valid_*_state_zip` into a single `expect_column_values_to_be_valid_zip_based_on_location`. This will decrease code duplication and will support any location filtering for the whole globe.

I'm available to make this refactoring

**Comment by talagluck** [comment]
Hi @sp1thas - thank you for raising this.

There are a couple of different philosophies for Expectations - one philosophy is to have fewer Expectations with more parameters, while another is to have more Expectations that are single purpose. We haven't necessarily settled on one approach vs another. The first approach is certainly more efficient, but the second one provides a more effective implementation of Expectations as docs, since, at a glance, a user can tell what an Expectation is trying to do.

The user who contributed these Expectations in particular expressed that splitting them up had utility for them, since it meant that this documentation would be more effective. That said, if you feel that you would like a single, merged Expectation, please feel to contribute one! If you are able to provide support for multiple countries, that would also increase the functionality! When it comes to our experimental Expectations within our contrib package, we have been fairly flexible, since we want to enable users to contribute whatever Expectations will meet their needs.

I'm going to close this issue for now, but I look forward to seeing a merged version of this Expectation - thanks!
