### ISSUE TITLE
Include_unexpected_rows for not null check

### ISSUE THREAD

**Issue by Vijayitsme** [fivetran/great_expectations#5627]
I am working on a project where in the data pipeline validation has to be carried out frequently to validate the data once arrived. In that case, while performing a GE validation "**expect_column_values_to_not_be_null**" with result format as **COMPLETE** and **include_unexpected_rows = True**. I expect to get the failed validation records as unexpected rows. **But all I get is unexpected rows =  null**. This is required so as to move the null records as a whole to exception zone and process is separately in the pipeline. 
I am working with **SPARK DATAFRAME**

**Expected Solution:**
Expect the display of **unexpected_rows** with all the failed records. [Even when the output may become clumsy at times] for ease in further analysis.

**Tried with:**
I have tried to get the unexpected records through custom validation for null checks/through regex/columns in set etc but all those methods are treating the null values as missing count and not providing the output as unexpected row.

**Other than not null all the other validations display the unexpected records when it is set to true**

**Comment by AFineDayFor** [comment]
Howdy @Vijayitsme :wave: thanks for raising the with us and being a part of the community :bow:

We'll share this with the team. Thank you so much for seeing something and saying something 🌻 🔬

**Comment by AFineDayFor** [comment]
Howdy @Vijayitsme, at this time the discussion from the team was that if no information is yielded, the metrics would not be ran. :bow:

**Comment by VLALLARD** [comment]
@AFineDayFor  - We are also experiencing this same issue.  We would like to have this output to be able to send to our team members to be able to correct issues with the data. However, for this particular rule, because it outputs as unexpected rows = null, the rows do not produce to include with the other data rows that fail with other GX rules in our ruleset.  Our job is setup similarly as the original poster and we do not have this issue with other GX rules.  Please reconsider to make the output react the same as other rules.
