### ISSUE TITLE
Usage statistics config sync should be skipped when disabled 

### ISSUE THREAD

**Issue by safwank** [fivetran/great_expectations#5637]
**Describe the bug**
A recent [update](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/data_context/data_context.py#L367) to `DataContext` to sync the config for usage statistics is causing DAGs hosted in AWS MWAA to fail. This is because in MWAA the filesystem used to host Airflow DAGs is read-only, so `great-expectations.yml` can't be updated at runtime. This isn't an issue in itself, except I would expect the config update to be _skipped_ if anonymous usage statistics is _disabled_, but apparently this isn't the case.

**To Reproduce**
1. Create a DAG that uses `ge`
2. Disable usage statistics by setting `anonymous_usage_statistics.enabled: false` in `great_expectations.yml`
3. Deploy and run DAG in MWAA
4. DAG execution fails because of `OSError: [Errno 30] Read-only file system`

**Expected behavior**
The config shouldn't be updated when usage statistics is disabled. 

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.16
 - Airflow Version: AWS MWAA v2.2.2

**Additional context**
Let me know if this is the expected behaviour.

**Comment by talagluck** [comment]
Thanks for raising this, @safwank! Resolved by #5644.

**Comment by deathwebo** [comment]
Hey @safwank the PR mentioned above solved the issue for you ? I'm in a similar situation, but instead of AWS MWAA, I'm running the airflow helmchart in kubernetes and the file system is read-only.

Disabling the user statistics and pointing the validation store to s3 don't seem to prevent GX from trying to write to the `great_expectations/uncommitted` directory.

Sorry for reviving a closed issue, but this looked like a similar situation to mine.

**Comment by safwank** [comment]
@deathwebo It's been awhile, but if memory serves the PR did resolve the issue in my case.
