### ISSUE TITLE
Dask as execution engine

### ISSUE THREAD

**Issue by NickSchouten** [fivetran/great_expectations#5816]
We would like to use Dask as an execution engine for great expectations.

Up until https://great-expectations.readthedocs.io/en/0.13.8/intro.html this was also mentioned under `Key Features` `Expectations` as a future step in the docs.
What happened for this to be removed? Is this still on the roadmap?
Is there an initiative or open pull request were we could help?

Kind regards,
Nick

**Comment by talagluck** [comment]
Hi @NickSchouten - thanks for this! When we listed this in the linked docs, I believe it was more as an example of another execution engine integration that we would like to have, rather than a short-term goal. It is still on our roadmap, but I don't believe we have any scheduled plans to build this internally. If you are interested in working on an integration, please let us know! We are happy to offer guidance and support through the process.

**Comment by NickSchouten** [comment]
Hi @talagluck, 
We would be interested in building this, but going through source it seems hard to determine what would need to be created as some pandas and spark classes seem to be deprecated code. Is there a summation of what classes and functions need to be made/edited for dask to work?

**Comment by talagluck** [comment]
Hi @NickSchouten - that's exciting!

The main code you'll want to reference will be for the `ExecutionEngines` - you will want to create a new Dask Execution Engine. You will also need to add support to many or all of the Metrics so that these support Dask as a new type alongside SqlAlchemy, pandas, and Spark.

You can totally ignore everything in the `data_asset` and 'dataset' directories, and all of the backend specific `datasource` files (e.g. `pandas_datasource`). These are all for V2, which we no longer fully support.

An [experimental PR for polars](https://github.com/great-expectations/great_expectations/pull/5914/files) has actually been opened recently that would be great to provide some direction. This has just come in in draft form, so I would not say that it is definitive, but it should provide a good starting point.

Once you open up an initial PR, we will be able to collaborate more fully and provide additional support. But please let us know if you need help or get stuck before then. Looking forward!

**Comment by PaoloLeonard** [comment]
Hey @talagluck !
Could you confirm that Dask support is still in your roadmap? If that's still the case then we would be more than happy to start working on it at dataroots.
Additionally, does your last comment still stand as a broad "guide" to start implementing Dask as `ExecutionEngine` ?

Thanks in advance !

**Comment by austiezr** [comment]
Hey @PaoloLeonard! Thanks for resurfacing this. We're actively discussing this internally, and we'll reach out to offer some guidance here and discuss implementation soon!

**Comment by austiezr** [comment]
Hey @PaoloLeonard / @NickSchouten. After much review by the core team, we don't have a path forward here at this time. We're unable to prioritize supporting a new Execution Engine at this time, given the level of effort required to introduce this functionality as robustly as other Execution Engines. For now, we've captured this Feature Request, and will continue to discuss this internally as GX develops. Happy to leave this Issue open for discussion over the coming week, after which we'll close this out. 🙇

**Comment by PaoloLeonard** [comment]
Alright, thanks for the heads up :D
