### ISSUE TITLE
How to run checkpoint on all Batches instead of by default 1.

### ISSUE THREAD

**Issue by rishabhreply** [fivetran/great_expectations#6131]
I am using great expectations to run on csv files stored on S3 like this-
s3://bucket-name/folder1/**sub-folder1**/bonus.csv
s3://bucket-name/folder1/**sub-folder2**/bonus.csv

I built a checkpoint with following config-
```
        checkpoint_config = {
            "class_name": "SimpleCheckpoint",
            "validations": [
                {
                    "batch_request": {
                        "datasource_name": self.data_source_name + "_datasource",
                        "data_connector_name": "default_inferred_data_connector_name",
                        "data_asset_name": "DEFAULT_ASSET_NAME",
                        "batch_spec_passthrough": {"reader_options": {"sep": "|", "header": "true"}},
                    },
                    "expectation_suite_name": self.data_source_name + "_1st_suite",
                }
            ],
        }
```
On running this checkpoint it checks only the csv under the **sub-folder2** (s3://bucket-name/folder1/**sub-folder2**/bonus.csv). I want the check to also run over the csv under **sub-folder1**.  In my batch request list, I can see an ordered dict with two requests. I went through many documentation pages but could not find the exact way of achieving this. Please help, thank you!

**Comment by MoBoo** [comment]
I have the same issue... 
I dug through some code and found some hints on why this behavior is the case:

In `great_expectations/validator/validator.py:1413` the `active_batch_id` is set as the last item of the `batches` in the `Validator` object. This `active_batch_id` is then used in the construction of the ExpectationsGraph ( `great_expectations/validator/validator.py:1024` and somewhere down the rabbit hole passed to the execution_engine.
In my testing it is in the `great_expectations/execution_engine/pandas_execution_engine.py:588` `get_compute_domain()` method which calls `get_domain_records()` which finally in line 460 uses `batch_id = domain_kwargs.get("batch_id")` to get the dataframe of this exact batch (line 471).

I also found this [documentation page](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_get_one_or_more_batches_of_data_from_a_configured_datasource/#steps-loading-one-or-more-batches-of-data), which, atleast for me, describes the desired behavior from this issue.

I threw together a test to demonstrate the issue: the attached script defines two data batches (data_1.csv (only zeroes) and data_2.csv (only twos)). When running this validator (`validator.expect_column_values_to_be_between("value", min_value=0, max_value=1)`) against the batch of both files (data_1.csv and data_2.csv) the validation passes (which it should not since the validator does not match data_2.csv), but fails when running only against data_2.csv. This effect can be observed then uncommenting line 50.
[issue_6131_test.py.txt](https://github.com/great-expectations/great_expectations/files/9737729/issue_6131_test.py.txt)

**Comment by rishabhreply** [comment]
> I have the same issue... I dug through some code and found some hints on why this behavior is the case:
> 
> In `great_expectations/validator/validator.py:1413` the `active_batch_id` is set as the last item of the `batches` in the `Validator` object. This `active_batch_id` is then used in the construction of the ExpectationsGraph ( `great_expectations/validator/validator.py:1024` and somewhere down the rabbit hole passed to the execution_engine. In my testing it is in the `great_expectations/execution_engine/pandas_execution_engine.py:588` `get_compute_domain()` method which calls `get_domain_records()` which finally in line 460 uses `batch_id = domain_kwargs.get("batch_id")` to get the dataframe of this exact batch (line 471).
> 
> I also found this [documentation page](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_get_one_or_more_batches_of_data_from_a_configured_datasource/#steps-loading-one-or-more-batches-of-data), which, atleast for me, describes the desired behavior from this issue.
> 
> I threw together a test to demonstrate the issue: the attached script defines two data batches (data_1.csv (only zeroes) and data_2.csv (only twos)). When running this validator (`validator.expect_column_values_to_be_between("value", min_value=0, max_value=1)`) against the batch of both files (data_1.csv and data_2.csv) the validation passes (which it should not since the validator does not match data_2.csv), but fails when running only against data_2.csv. This effect can be observed then uncommenting line 50. [issue_6131_test.py.txt](https://github.com/great-expectations/great_expectations/files/9737729/issue_6131_test.py.txt)

Thanks for confirming this issue. How did you fix it then in your case?

**Comment by AFineDayFor** [comment]
Howdy @rishabhreply and @MoBoo :wave: thank you both for you raising this :bowing_woman:

We'll raise this with the team; however, we'll also be watching for @MoBoo's reply as well. Thank you both so very much for identifying this, it's greatly appreciated.

**Comment by MoBoo** [comment]
Great this issue is picked up :D

> Thanks for confirming this issue. How did you fix it then in your case?
> however, we'll also be watching for @MoBoo's reply as well.

Haven't yet. It is also still an open issue on my end. Looking into the code i also don't see an easy way for a fix or PR without breaking things on multiple other ends ... ^^

Currently my best bet is to work around this issue until it can be resolved by the devs :)
For example one could define the checkpoint validation batches for each, in your example, sub-folder. This would work if one can define the "moving parts" upfront. Won't be possible for every use case tho (e.g. validating an arbitrary amount of files in defined batch, which this issue should be about)

**Comment by rishabhreply** [comment]
Thanks @AFineDayFor . I hope it gets fixed soon, because this affects the whole point of having great_expectations in practice. I also think the documentation can be improved a lot. Many times only particular cases are described but there is no information about other obvious cases and those cases can be implemented, it's just not documented. 

@MoBoo , thanks for sharing the info. Yes, I implemented in this way. One needs to get the lenght of batch request and then define batch requests one for each batch(sub-folder, in my case) by defining **index** under **data_connector_query**.

**Comment by AFineDayFor** [comment]
Howdy @rishabhreply and @MoBoo, thank you both for your patience :bow:

So for clarity's sake, currently we do not support this to the extent you'd want; you'd have to provide the batch ID as you currently are; however, we'll be bringing it up with the engineering component, for some clarity on how we want to go forward still.

Thank you both so very much. Keep an eye on the changelog/roadmap?

As a brief aside, is it just me or does anyone get a small bit of joy when autocorrect changes "Changelog" to "Changeling" like it's a DM trying to keep us on task in a game of DND 5e?

**Comment by jsaizlomas** [comment]
Hi everyone! Are there any updates with this issue?

**Comment by fbardos** [comment]
I have the same problem, trying to evaluate multiple .parquet files.
But it doesn't matter if i have set a `data_query_connector` (4 files to check) or not (30+ files to check): Only one file/batch gets selected inside the `Validator`:
* In Data Docs, only one `path` is displayed: 
![image](https://user-images.githubusercontent.com/15113366/224486340-63ef8371-7412-41ce-b085-ab483baab9a7.png)
* I added an Expecation, which should fail when all 4 files get evaluated. But the test is successful.


I used a debugger to track down the possible problem (not sure, if I got the correct spot where only one `Batch` gets selected):

First, inside `ActionListValidationOperator.run()`, all assets get collected for validation (using `Checkpoint.run`):
https://github.com/great-expectations/great_expectations/blob/7827b3fdd95f1af0e05eded2f79aee8fed0d0da7/great_expectations/validation_operators/validation_operators.py#L347-L348
In my example, `assets_to_validate` is a list containing one single `Validator`:
````bash
ipdb> assets_to_validate
[<great_expectations.validator.validator.Validator object at 0x7f62d81e17e0>]
````
Inside this validator, there are 4 potential `Batches` to check:
````bash
ipdb> pp assets_to_validate[0].batches
OrderedDict([('91e75776c43f968d4839e01af6678bd3',
              <great_expectations.core.batch.Batch object at 0x7efec0204b50>),
             ('b6b56dae418ce712edecf59890ef4e5f',
              <great_expectations.core.batch.Batch object at 0x7efec03a9600>),
             ('280ac1df73d9bf85b689dbe1f87692e6',
              <great_expectations.core.batch.Batch object at 0x7efec04453c0>),
             ('a0ee14e320e12ca371c3f71dccf395f2',
              <great_expectations.core.batch.Batch object at 0x7efec06edc60>)])
````

According to a comment by @jdimatteo in the code, it is possible, that the length of `assets_to_validate` is 1, but the method `ActionListValidationOperator.run()` gets called multiple times by `Checkpoint.run()`:
https://github.com/great-expectations/great_expectations/blob/7827b3fdd95f1af0e05eded2f79aee8fed0d0da7/great_expectations/validation_operators/validation_operators.py#L336-L343

In my example, this is not the case. The method gets only called once. Therefore, I assume, that all `Batches` have to be called using this single `Validator` object.

So, going futher down the code in the method: The method `_build_batch_from_item(item)` gets called, but instead of a `Batch`, the `Validator` itself gets passed:
https://github.com/great-expectations/great_expectations/blob/7827b3fdd95f1af0e05eded2f79aee8fed0d0da7/great_expectations/validation_operators/validation_operators.py#L349
````bash
ipdb> batch
<great_expectations.validator.validator.Validator object at 0x7efec03a97b0>

````
Then, `ActionListValidationOprator._run_actions()` gets called. But again, with a `Validator` as `batch` parameter:
https://github.com/great-expectations/great_expectations/blob/7827b3fdd95f1af0e05eded2f79aee8fed0d0da7/great_expectations/validation_operators/validation_operators.py#L382-L415

Inside `ActionListValidationOprator._run_actions()`
````bash
ipdb> batch
<great_expectations.validator.validator.Validator object at 0x7fed39fc3a00>
ipdb> batch.active_batch_id
'a0ee14e320e12ca371c3f71dccf395f2'
````
The type hint is maybe wrong, it expects:
https://github.com/great-expectations/great_expectations/blob/7827b3fdd95f1af0e05eded2f79aee8fed0d0da7/great_expectations/validation_operators/validation_operators.py#L430-L432

At the end, there is no Exception. The run is successful, but only selecting one file from my s3 bucket.

Sorry for the long comment. I just wanted to share my analysis with the debugger and hoping, this helps you resolving this issue.

**Comment by billdirks** [comment]
Hi - thanks for raising this. This is a really cool idea. We likely won’t be able to prioritize this in the immediate future, so I’m going to close this for now, but we’ve logged this product feedback and will be in touch if and when we are able to work on it.

I do have a workaround that you may be able to use. You can specify multiple validations, one for each batch, to a checkpoint configuration. When you run the checkpoint a validation will be run on each batch. Here is a code snippet I used to do this. When this snippet completes the data docs show a validation result for each batch.
```
import great_expectations as gx

context = gx.get_context()
my_datasource = context.datasources["my_datasource"]

batches = my_datasource.get_batch_list_from_batch_request(
    gx.core.batch.BatchRequest(
        datasource_name="my_datasource",
        data_connector_name="configured",
        data_asset_name="myasset",
    )
)

validations = []
for i in range(len(batches)):
    batch_request = gx.core.batch.BatchRequest(
        datasource_name="my_datasource",
        data_connector_name="configured",
        data_asset_name="myasset",
        data_connector_query={"index": i},
    )
    validations.append({"batch_request": batch_request})

results = context.run_checkpoint(
    checkpoint_name="my_checkpoint",
    run_name="test_run",
    validations=validations,
)
context.open_data_docs()
```

Something similar to this should work for any datasource. For this example, I was using a `PandasExecutionEngine` with a directory with path `/path/to/data` containing multiple files named `data_XXXX.csv` each of which corresponded to a batch. Here is my datasource configuration block from my great_expectations.yml file:
```
datasources:
  my_datasource:
    class_name: Datasource
    module_name: great_expectations.datasource
    data_connectors:
      configured:
        assets:
          myasset:
            class_name: Asset
            group_names:
              - year
            module_name: great_expectations.datasource.data_connector.asset
            pattern: data_(\d{4})\.csv
        class_name: ConfiguredAssetFilesystemDataConnector
        module_name: great_expectations.datasource.data_connector
        base_directory: /path/to/data
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
```

**Comment by ramdhilip** [comment]
Dear @billdirks,

Thank you for your solution, which has facilitated the addition of multiple batches into the checkpoint. However, an issue has surfaced where the validation process seems to run solely on the last dataset, resulting in the validation result encompassing only the outcomes of that particular dataset.

Upon reviewing the checkpoint's YAML file and the provided validation results, it's evident that while the YAML file adequately captures all batch details, the validation output appears to focus solely on the final batch.

**mycheckpoint.yml**
`name: mycheckpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template:
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: mydatasource
      data_asset_name: mydataasset
      options:
        path: mydirectory/part-0001-0.snappy.parquet
      batch_slice:
    expectation_suite_name: myexpectationsuite
  - batch_request:
      datasource_name: mydatasource
      data_asset_name: mydataasset
      options:
        path: mydirectory/part-0002-0.snappy.parquet
      batch_slice:
    expectation_suite_name: myexpectationsuite
  - batch_request:
      datasource_name: mydatasource
      data_asset_name: mydataasset
      options:
        path: mydirectory/part-0003.snappy.parquet
      batch_slice:
    expectation_suite_name: myexpectationsuite
  - batch_request:
      datasource_name: mydatasource
      data_asset_name: mydataasset
      options:
        path: mydirectory/part-0004-0.snappy.parquet
      batch_slice:
    expectation_suite_name: myexpectationsuite
  - batch_request:
      datasource_name: mydatasource
      data_asset_name: mydataasset
      options:
        path: mydirectory/part-0005-0.snappy.parquet
      batch_slice:
    expectation_suite_name: myexpectationsuite
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:`

Validation Result: **mydatasource-mydataasset.json**
`
{
  "evaluation_parameters": {},
  "meta": {
    "active_batch_definition": {
      "batch_identifiers": {
        "path": "mydirectory/part-0005-0.snappy.parquet"
      },
      "data_asset_name": "mydataasset",
      "data_connector_name": "fluent",
      "datasource_name": "mydatasource"
    },
    "batch_markers": {
      "ge_load_time": "20240303T075815.317795Z",
      "pandas_data_fingerprint": "4565fdhdfyu567567tyu5567"
    },
    "batch_spec": {
      "path": "s3a://dev/mydirectory/part-0005-0.snappy.parquet",
      "reader_method": "read_parquet",
      "reader_options": {}
    },
    "checkpoint_id": null,
    "checkpoint_name": "mycheckpoint",
    "expectation_suite_name": "myexpectationsuite",
    "great_expectations_version": "0.18.10",
    "run_id": {
      "run_name": null,
      "run_time": "2024-03-03T07:58:07.257541+00:00"
    },
    "validation_id": null,
    "validation_time": "20240303T075815.337586Z"
  },
  "results": [
    {
      "exception_info": {
        "exception_message": null,
        "exception_traceback": null,
        "raised_exception": false
      },
      "expectation_config": {
        "expectation_type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "mydatasource-mydataasset",
          "column": "id"
        },
        "meta": {}
      },
      "meta": {},
      "result": {
        "element_count": 1,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": [],
        "partial_unexpected_list": [],
        "unexpected_count": 0,
        "unexpected_percent": 0.0
      },
      "success": true
    },
    {
      "exception_info": {
        "exception_message": null,
        "exception_traceback": null,
        "raised_exception": false
      },
      "expectation_config": {
        "expectation_type": "expect_table_row_count_to_be_between",
        "kwargs": {
          "batch_id": "mydatasource-mydataasset",
          "max_value": 11,
          "min_value": 1
        },
        "meta": {}
      },
      "meta": {},
      "result": {
        "observed_value": 1
      },
      "success": true
    }
  ],
  "statistics": {
    "evaluated_expectations": 2,
    "success_percent": 100.0,
    "successful_expectations": 2,
    "unsuccessful_expectations": 0
  },
  "success": true
}
`

Below is my code snippet.

` 

    data_asset = context.datasources[ds_name].get_asset(asset_name)

    batch_request = data_asset.build_batch_request()

    batch_list = data_asset.get_batch_list_from_batch_request(batch_request=batch_request)

    validations = [
        {"batch_request": batch.batch_request, "expectation_suite_name": suite_name}
        for batch in batch_list
    ]

    checkpoint = context.add_or_update_checkpoint(
        name=checkpoint_name,
        validations=validations
    )

    checkpoint_result = checkpoint.run()

    context.build_data_docs()
    context.open_data_docs()
    `
   
    
It's apparent from the provided mydatasource-mydataasset.json that the validation results only reflect the outcomes of the last batch, failing to aggregate results across all batches.

We would appreciate any insights or suggestions you might have to address this issue effectively.
