### ISSUE TITLE
inbuilt serve command to display data_docs on webserver

### ISSUE THREAD

**Issue by tooptoop4** [fivetran/great_expectations#6285]
right now data_docs html files can be written to filesystem but then i need to setup my own nginx.etc to serve it on UI to multi users.
feature request is an equivalent command to: https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/task/serve.py

**Comment by AFineDayFor** [comment]
Howdy @tooptoop4 👋 that sounds like an astonishingly cool contribution if you're willing to submit it 🔬 

You may also be able to leverage actions to this end.

**Comment by talagluck** [comment]
Hi @tooptoop4 - it is possible to do this already using cloud backends, such as S3. This is also a feature offered by GX Cloud - you can see more information here: https://greatexpectations.io/gx-cloud.

I'm going to close this for now, since we won't be able to prioritize this in OSS. That said, we've logged the request, and if you are interested in making a contribution, please feel free to open a new issue or PR.
