### ISSUE TITLE
Action Failure is affecting other actions

### ISSUE THREAD

**Issue by itaise** [fivetran/great_expectations#6364]
Hi,
In our set up, we have 2 actions: update data docs and slack notification. 
We noticed that if one action failed (e.g. - update data docs failed because of S3 connection issue), the next action - send slack alert will not happen. 
I think the exception from the action shouldn't "cancel" the next action - the slack alert should be sent even if there is an issue with updating the data docs. Because the user (in our case, a dag owner) won't know about the failure otherwise.
What do you think?
thanks a lot :) 
CC: @talagluck

**Comment by talagluck** [comment]
Hi @itaise! We've had some discussion internally, and would love to better understand some potential designs. For instance, currently the Slack Notification Action send the results of a Validation, but I don't think it has the capacity to render an error instead. So there is a question as to whether we would modify the existing Slack Notification Action to process errors, or to have a new Action which would do that.

Essentially, we think the solution here would require a configuration parameter to determine if a failed action is “Blocking”, so that if it raises an error, do we abort or not?

There are a couple of ways to solve this:
- Something like “continue_on_error = True”. Should we pass on error information in this case in some way?
- if(success) action X else action Y ← this is the most likely

If you can put together an initial design for this, we can review, iterate, and work with you on a contribution! Let us know what you think.

**Comment by austiezr** [comment]
Hey @itaise! Reaching out to gauge if this is still something you're interested in approaching.

**Comment by austiezr** [comment]
Hey @itaise! Wanted to let you know we've captured this for our internal backlog; we'll leave this Issue open for the next week if you have any further input here, otherwise we'll close out.

**Comment by itaise** [comment]
Hi, 
So, I am interested in developing this feature - Adding an optional  flag of "continue_on_error" = True to an action sounds great to me, but Im not sure Ill have the time to do it this coming month lets say.

**Comment by anthonyburdi** [comment]
That sounds great @itaise! I'll close out this issue and when you have a chance to submit a PR our team can collaborate with you on the design and implementation.
