### ISSUE TITLE
Data Assist Onboarding Profilier error

### ISSUE THREAD

**Issue by dollyBa** [fivetran/great_expectations#6417]
Hi,

I am using great expectations on Databricks with my data source as Snowflake. When I'm running the Profilier on a table that has a numeric column with all NULL values, it is throwing the following error:
**AttributeError("'list' object has no attribute 'dtype'")**

**To Reproduce**
Code used:
```
data_assistant_result = context.assistants.onboarding.run(
          batch_request=batch_request,
        estimation="flag_outliers"
      )
try:
    suite = context.create_expectation_suite(expectation_suite_name=expectation_suite_name)
    print(f'Created ExpectationSuite "{suite.expectation_suite_name}".')
except Exception as e:
    print(f'Unable to Create ExpectationSuite "{expectation_suite_name}". It already exists!! Please select a UNIQUE name.')

expectation_suite = data_assistant_result.get_expectation_suite(
          expectation_suite_name=expectation_suite_name
      )

context.save_expectation_suite(
          expectation_suite=expectation_suite, discard_failed_expectations=False
      )
```

**Expected behavior**
Ideally it should not throw error for a column having all NULL values. This error is being thrown only for numeric columns. It is not throwing this kind of error of a varchar column containing all NULLs.

**Environment:**
 - Operating System: Windows
 - Workspace: Databricks
 - Great Expectations Version: 0.15.25

**Comment by alexsherstinsky** [comment]
Hello, @dollyBa -- thank you very much for reporting this issue.  This one may take a little bit more effort to troubleshoot, and I am hoping that we can work together on this.  To start, we need to do the following:
1) Please run your `data_assistant_result = context.assistants.onboarding.run` method call with `estimation="exact"` (or omit the `estimation` argument altogether) and let me know if the same situation happens.
2) In all cases, please provide the full exception stacktraces.
3) In order to reproduce the problem in DataBricks, is there any way you could give me access to a test environment as well as share your DataBricks notebook -- in particular, I would be interested in how the Snowflake/Databricks environment is configured as well as the contents of the smallest possible representative dataset, needed to reproduce the problem.

Thank you very much in advance, and if it helps, please feel free to reach out in the GX Slack community (will report all results here as well).

**Comment by alexsherstinsky** [comment]
@dollyBa I am hoping that my suggestions helped. I am closing this issue for now. Please feel free to reopen and let us know at any time. Thank you very much for using GX!
