### ISSUE TITLE
GE_TEMP Tables Pollute Data Source 

### ISSUE THREAD

**Issue by txiaptc** [fivetran/great_expectations#6923]
Hi there,

I use SqlAlchemy to connect an Oracle database via the Profiler feature. There are lots of GE_TEMP created in the Oracle database, without automatic deletion. This situation somehow pollutes the DB. Is there any way to remove these GE_TEMP tables sophisticated?

![ge_temp](https://user-images.githubusercontent.com/123573579/214607875-123347a6-ee72-45e7-8509-6d8676c8b1a2.PNG)

Thanks,
Tian

**Comment by talagluck** [comment]
Hi @txiaptc - thanks for your question. Since Oracle is not a fully support backend, GX is not set up to properly manage temp tables with Oracle. Have you tried setting `create_temp_table` to False [as described here](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource/#5-add-the-sqlalchemy-execution-engine-to-your-datasource-configuration)? If you've tried that, and it doesn't work, then you would need to remove them manually, for now.

**Comment by txiaptc** [comment]
Hi @talagluck,
Thanks for sharing the information. The link you shared above about the create_temp_table navigated to a wrong web page. Could you send me another one, please?

**Comment by talagluck** [comment]
Apologies, @txiaptc - updated.

**Comment by txiaptc** [comment]
Issue solved by disabling create_temp_table
