### ISSUE TITLE
Observed Value is not displayed correctly

### ISSUE THREAD

**Issue by andrrreasss** [fivetran/great_expectations#7077]
**Describe the bug**
If you run expectations expect_column_values_to_be_null with a custom query and it does not return a single line in the interface, the Observed Value is not displayed correctly

**To Reproduce**
1. Define a RuntimeBatchRequest with a custom query that does not return a single line. e.g. select 1 as id where false
2. Run expect_column_values_to_be_null for this RuntimeBatchRequest
3. build_data_docs
4. See error in Observed Value

**Expected behavior**
100% null? But there are no null values there.

**Environment (please complete the following information):**
 - Linux
 - Great Expectations Version:  0.15.47

**Additional context**
![2023-02-08_16-13](https://user-images.githubusercontent.com/41391831/217526780-ba8d8a20-5584-4683-90ee-797aeb5b85f2.png)

**Comment by andrrreasss** [comment]
I have a query that returns rows with an error. And it doesn't return any rows if there are no errors. I first applied expect_table_row_count_to_equal, value=0. But in this case, it didn't return any erroneous rows to me if there were any when I set 

result_format = {"result_format": "SUMMARY",
                 "unexpected_index_column_name": ["id"]
                 }

Then I tried using expect_column_values_to_be_null.

How to do it more correctly in a case like this?

**Comment by austiezr** [comment]
Hey @andrrreasss ! Thanks for raising this. We'll review this behavior and be in touch.

**Comment by alexsherstinsky** [comment]
Hello, @andrrreasss  -- since you reported this issue, GX has undergone a lot of improvements. Would it be possible for you to try your usecase again and let us know whether or not it works? Here are a couple of specific requests:

* Please use the "Fluent Datasources" approach -- this is a new, more intuitive way, to connect to data.  In fact, `RuntimeBatchRequest` is no longer used/needed -- there is a simpler way to specify your custom query.
* Please report your code with full error stack trace -- with as much detail as possible.

Thank you very much.

**Comment by alexsherstinsky** [comment]
@andrrreasss I am hoping that my suggestions helped.  I am closing this issue for now. Please feel free to reopen and let us know at any time.  Thank you very much for using GX!
