### ISSUE TITLE
Inconsistent file read with delimeter

### ISSUE THREAD

**Issue by Pratush12** [fivetran/great_expectations#7093]
**Describe the bug**
I have a csv file attached, while profiling it, I am passing the below inside batch request:

[dummy_file.csv](https://github.com/great-expectations/great_expectations/files/10700182/dummy_file.csv)

batch_request = BatchRequest(
    datasource_name=f"dataframe_{data_set}_source",
    data_connector_name=f"dataframe_{data_set}_data_connector",
    data_asset_name=f"{data_set}_data_asset",
    batch_spec_passthrough={"reader_options": {"sep": delimiter,"header": True}})

But there are some columns like YEAR,DIR_TOT_REVENUE etc that should have been integer datatype but in expectation suite it is TYPE LIST : char,nchar,ntext,text etc

I tried reading those file with spark dataframe and dtypes for them were int only.
**To Reproduce**
Read the attached data with the above batch request.
Check the expectations for YEAR column, it will be string.

Read the data using pyspark, the dtype for YEAR will be int.

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: Windows
 - great-expectations =0.15.28

**Comment by austiezr** [comment]
Hey @Pratush12! Thanks for reaching out.

I'd be interested to know exactly how you're reading this data with pyspark; [by default, spark will not infer schema](https://spark.apache.org/docs/2.2.0/api/python/pyspark.sql.html?highlight=inferschema). As you're not passing spark a schema or passing the `inferSchema` option above, the behavior you're experiencing with GX is the expected behavior. Unless you're passing a schema when reading this data directly with pyspark, or passing the `inferSchema` option as `true`, expected behavior with pyspark *should* be the same.

Including `inferSchema` in your `reader_options` will give you the behavior you're looking for:

```python
batch_spec_passthrough={
    "reader_options": {
        "sep": delimiter,
        "header": True,
        "inferSchema": True
    }
}
```

Closing this out for now; if you're unable to get the behavior you're looking for, feel free to re-open!
