### ISSUE TITLE
Lowercase column name handling w/Snowflake bug reoccurring w/expectation expect_compound_columns_to_be_unique

### ISSUE THREAD

**Issue by cyearee** [fivetran/great_expectations#7145]
**Describe the bug**
Running checkpoint w/expectation expect_compound_columns_to_be_unique against a Snowflake table with lowercased columns raising invalid identifier exception.

**To Reproduce**
1. Here is the erroring expectation snippet: 
~~~
    {
      "expectation_type": "expect_compound_columns_to_be_unique",
      "kwargs": {
        "column_list": [
          "id",
          "type"
        ]
      },
      "meta": {}
    }
~~~
2. Batch request snippet of checkpoint run with above expectation:
~~~
  - batch_request:
      datasource_name: ${SOURCE_NAME}
      data_connector_name: default_configured_data_connector_name
      data_asset_name: ${SNOWFLAKE_VIEW}
      data_connector_query:
        index: -1
~~~
3. Getting an error "snowflake.connector.errors.ProgrammingError) 000904 (42000): SQL compilation error: error line 6 at position 11 invalid identifier 'ID'". Here is the snippet of a sql that it's trying to run:
~~~
SELECT "id", "type"
  FROM (SELECT original_table_clause."id" AS "id",
               original_table_clause."type" AS "type",
               ...
               group_counts_subquery._num_rows AS _num_rows
          FROM (SELECT "id",
                       "type",
                       ...
                  FROM (SELECT *
                          FROM ge_temp_13f3481e
                         WHERE NOT (id IS NULL AND type IS NULL)) AS anon_1) AS original_table_clause -- ERROR HERE
               JOIN (SELECT "id", "type", COUNT(*) AS _num_rows
                       FROM (SELECT "id",
                                    "type",
                                    ...
                               FROM (SELECT *
                                       FROM ge_temp_13f3481e
                                      WHERE NOT (id IS NULL AND type IS NULL)) AS anon_1) AS original_table_clause -- ERROR HERE
                      GROUP BY "id", "type") AS group_counts_subquery
               ON group_counts_subquery."id" = original_table_clause."id" AND group_counts_subquery."type" =
                                                                              original_table_clause."type") AS records_with_grouped_column_counts_subquery
 WHERE ... 
~~~

**Environment (please complete the following information):**
 - Operating System: mac
 - Great Expectations Version: 0.15.48

**Comment by talagluck** [comment]
Thanks for raising this, @cyearee - we will review and be in touch.

**Comment by lukedyer-peak** [comment]
It looks to be an issue with how great expectations uses quote identifiers with snowflake.  Rather than leaving it to snowflake to do it's atypical use uppercase columns internally both upper and lower case columns are used.  [Snowflake docs](https://docs.snowflake.com/en/sql-reference/identifiers-syntax#label-identifier-casing)

I have the same issue cropping up in this expectation (`expect_compound_columns_to_be_unique`) and `expect_table_columns_to_match_set`.  I imagine it'll be causing lots of frustration with other users.

For `expect_compound_columns_to_be_unique` my error is:
```
great_expectations.exceptions.exceptions.MetricResolutionError: (snowflake.connector.errors.ProgrammingError) 000904 (42000): SQL compilation error: error line 6 at position 11
invalid identifier 'CUSTOMER_ID'
```

```sql
SELECT "customer_id", "updated_at"
FROM (SELECT original_table_clause."customer_id" AS "customer_id", original_table_clause."customer_id" AS customer_id_1, original_table_clause."customer_category" AS "customer_category", original_table_clause."customer_category" AS customer_category_1, original_table_clause.customer_subcategory AS customer_subcategory, original_table_clause.customer_subcategory AS customer_subcategory_1, original_table_clause."updated_at" AS "updated_at", original_table_clause."updated_at" AS updated_at_1, group_counts_subquery._num_rows AS _num_rows
FROM (SELECT "customer_id", customer_id, "customer_category", customer_category, customer_subcategory, "customer_subcategory", "updated_at", updated_at
FROM (SELECT *
FROM ge_temp_4efaebd4
WHERE NOT (customer_id IS NULL AND updated_at IS NULL)) AS anon_1) AS original_table_clause JOIN (SELECT "customer_id", "updated_at", count(*) AS _num_rows  -- ERROR HERE
FROM (SELECT "customer_id", customer_id, "customer_category", customer_category, customer_subcategory, "customer_subcategory", "updated_at", updated_at  -- NOTE DUPLICATE column names
FROM (SELECT *
FROM ge_temp_4efaebd4
WHERE NOT (customer_id IS NULL AND updated_at IS NULL)) AS anon_1) AS original_table_clause GROUP BY "customer_id", "updated_at") AS group_counts_subquery ON group_counts_subquery."customer_id" = original_table_clause."customer_id" AND group_counts_subquery."updated_at" = original_table_clause."updated_at") AS records_with_grouped_column_counts_subquery
WHERE records_with_grouped_column_counts_subquery._num_rows >= %(num_rows_1)s
LIMIT %(param_1)s]
[parameters: {'num_rows_1': 2, 'param_1': 20}]
```

Note in line 7 the duplicate column names!  The columns are stored as uppercase internally in the database but using lowercase columns in SQL is fine as they are coerced to uppercase by snowflake.  

The same happens for the following `expect_table_columns_to_match_set` exception (set up using the profiler):
```json
    {
      "expectation_type": "expect_table_columns_to_match_set",
      "kwargs": {
        "column_set": [
          "updated_at",
          "customer_id",
          "cumtomer_catergory",
          "customer_subcatergory"
        ],
        "exact_match": null
      },
      "meta": {
        "profiler_details": {
          "success_ratio": 1.0
        }
      }
    },
``` 
gives a passed expectation but  the data docs says

| Status | Expectation | Observed Value |
| ---- | ----- | ---- |
| X | Must have at least these columns (in any order): updated_at, customer_id, customer_category, customer_subcategory | ['customer_category', 'customer_category', 'customer_id', 'customer_id', 'customer_subcategory', 'customer_subcategory', 'updated_at', 'updated_at'] |

You can see that even the observed values are a bit messed up and duplicated here.


**Further notes:**
The table DDL as reported by snowflake is:
```sql
create table STAGE.CUSTOMER
(
    CUSTOMER_ID          VARCHAR,
    CUSTOMER_CATEGORY    VARCHAR,
    CUSTOMER_SUBCATEGORY VARCHAR,
    UPDATED_AT           TIMESTAMPNTZ
);


```

**System details:**
- great_expectations, version 0.15.50
- python 3.10.2
- snowflake-sqlalchemy       1.4.3
- SQLAlchemy                 1.4.41
- MacOS (but it's a snowflake issue)

**Comment by alexsherstinsky** [comment]
This has been fixed -- thank you so much @lukedyer-peak and @cyearee for bringing this case up and providing excellent examples for reproducing the issue.  The fix will be part of the next GX OSS release (targeted for Thursday, July 20, 2023).  Thanks!

**Comment by alexsherstinsky** [comment]
This has been fixed -- thank you so much @lukedyer-peak and @cyearee for bringing this case up and providing excellent examples for reproducing the issue. The fix will be part of the next GX OSS release (targeted for Thursday, July 20, 2023). Thanks!

**Comment by alexsherstinsky** [comment]
This has been fixed -- thank you so much @lukedyer-peak and @cyearee for bringing this case up and providing excellent examples for reproducing the issue. The fix will be part of the next GX OSS release (targeted for Thursday, July 20, 2023). Thanks!

**Comment by alexsherstinsky** [comment]
This has been fixed -- thank you so much @lukedyer-peak and @cyearee for bringing this case up and providing excellent examples for reproducing the issue. The fix will be part of the next GX OSS release (targeted for Thursday, July 20, 2023). Thanks!
