### ISSUE TITLE
'SELECT * \ninto #ge_temp_48320628 from <data asset> \nWHERE 1 = 1'

### ISSUE THREAD

**Issue by MinuraPunchihewa** [fivetran/great_expectations#7184]
I get the above error when I am trying to create a new expectation suite for a table in SQL Server.

I am using `great-expectations 0.15.49` and `SQLAlchemy 2.0.4`.

What is the problem here?

**Comment by andrrreasss** [comment]
https://github.com/great-expectations/great_expectations/issues/7020

**Comment by rdodev** [comment]
Hey @MinuraPunchihewa 👋 

As @andrrreasss points out, GX is not presently compatible with SQLAlchemy 2. We recommend downgrading to latest non-V2 version of SQLAlchemy.

**Comment by MinuraPunchihewa** [comment]
Hey @rdodev, thank you for your reply. I understand. Are there any plans to on-board SQLAlchemy 2?

**Comment by talagluck** [comment]
Hi @MinuraPunchihewa - yes, there are plans to add support for SQL Alchemy 2, and we are currently working on it, but we don't yet have a specific release date.

I'm going to close this ticket for now since this ticket is a duplicate, there is a workaround, and this work is in progress, but thanks for raising this.
