### ISSUE TITLE
docs display abnormal

### ISSUE THREAD

**Issue by eagleLiu82** [fivetran/great_expectations#7295]
**Describe the bug**
my linux machine has no browser,when I run command:
great_expectations docs build
normal finished,but web display abnormal.

**Expected behavior**
how can I display web normally?
![Uploading IMG_20230307_155535.jpg…]()

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]

**Additional context**

**Comment by talagluck** [comment]
Hi @eagleLiu82 - thanks for your question. What happens when you open the html files that are generated by the call to build the docs? If you have no browser, what are you expecting will happen?

**Comment by alexsherstinsky** [comment]
Hello, @eagleLiu82 -- following up on the situation: how do you display the results if your machine does not have a browser?

In addition, since the time of your filing this issue, GX has undergone a number of changes and improvements.

* In particular, the Comment-Line Interface (CLI) has been deprecated.
* Also, Fluent Datasource (FDS) has replaced the previous approach -- FDS is a new, more intuitive way, to connect to data.

Would it be possible for you to delete all contents from your `"great_expectations/uncommitted/validations"` and `"great_expectations/uncommitted/data_docs"` directories and rerun your use case again?

If errors occur again, please report your code with full error stack trace -- with as much detail as possible.

Thank you very much in advance (and thank you for using Great Expectations!).

**Comment by alexsherstinsky** [comment]
@eagleLiu82 I am hoping that my suggestions helped.  I am closing this issue for now. Please feel free to reopen and let us know at any time.  Thank you very much for using GX!
