### ISSUE TITLE
Create temporary table error

### ISSUE THREAD

**Issue by NikhilRajKotiL** [fivetran/great_expectations#7316]
**Describe the bug**
I am trying to connect to exasol database and successfully made the connection. While creating expectation suite great expectations is trying to create a temporary table in exasol db but there is no such concept as temporary table in exasol db. So is there a way to use this great expectations without creating temporary table. If yes, can you please tell how to do that

**Environment (please complete the following information):**
 - Windows 10
 - Great Expectations Version: 0.15.41

**Additional context**
this is the error i am getting,
ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [EXASOL][EXASolution driver]syntax error, unexpected TEMPORARY_, expecting VIRTUAL_SCHEMA_ [line 1, column 8] (Session: 1758015153839144960) (-6811776) (SQLExecDirectW)')
[SQL: CREATE TEMPORARY TABLE "ge_temp_29aaaca1" AS SELECT * 
FROM "I_PRAARYA".apro_assignments 
WHERE true]
(Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by talagluck** [comment]
Hi @NikhilRajKotiL - you can turn off temp table creation using the `create_temp_table` argument as described [in this doc.](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource/#5-add-the-sqlalchemy-execution-engine-to-your-datasource-configuration) That said, GX does not offer full support for Exasol, and doesn't test this connection at all, so this is uncharted territory. I'm going to close this issue for now, since this is an unsupported backend, and I believe you have a workaround. Thanks for raising!
