### ISSUE TITLE
Dump expectation suite directly to s3

### ISSUE THREAD

**Issue by nhm-7** [fivetran/great_expectations#7319]
**Is your feature request related to a problem? Please describe.**

When trying to save my expectation suite into s3, I can't do it. I can't save it locally and then upload it to s3.

**Describe the solution you'd like**
When trying to use a dump path like: `"s3://<bucket>/etc"`, it would be really useful if directly saves the json into s3.

**Describe alternatives you've considered**

Maybe we can use `smart_open` library to open and save the json file would be an interesting option to try as a spike.

**Additional context**

`df_feats_ge.save_expectation_suite("s3://my-bucket/my_expects.json")`

![image_720](https://user-images.githubusercontent.com/83786684/224110891-0930f44e-11ae-4772-b315-4af64cf08119.png)

Thank you!

**Comment by talagluck** [comment]
Hi @nhm-7 - when configuring your project in GX, you have the option of setting up your Expectations store where you'd like - this can be on your local filesystem or in one of the Cloud providers. Your Expectations store is a consistent place where your Expectation Suites get saved per project. Currently, the call to `DataContext.save_expectation_suite()` doesn't take a directory argument, since we expect that that location will be configured in your DataContext configuration. If you are interested in configuring an Expectations Store to save to S3, you can follow the guide here: https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3

I'm going to close this issue for now, but thanks for raising, and please don't hesitate to reach out if you have additional questions in the future.
