### ISSUE TITLE
Using great_expectation with streaming data/databricks autoloader

### ISSUE THREAD

**Issue by chhayavishwakarma** [fivetran/great_expectations#7337]
Hi everyone ,

I have implemented a data pipeline using autoloader bronze-->silver-->gold .

now while I do this I want to perform some data quality checks , and for that I'm using great expectations library.

However I'm stuck with below error when trying to validate the data

validator.expect_column_values_to_not_be_null(column="col1")

validator.expect_column_values_to_be_in_set(

   column="col2",

   value_set=[1,6]

)

MetricResolutionError: Queries with streaming sources must be executed with writeStream.start();

looks like great expectations can work with only static/batch data.

Can someone advise how can I go about getting it working ?

I followed below in my databricks notebook to get started with great_expectations

https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_databricks/

I couldn't find a documentation on streaming use cases. I have a customer who is looking to use it for streaming data

appreciate your support.

**Comment by alexsherstinsky** [comment]
Hello, @chhayavishwakarma -- thank you very much for reporting an error you encountered while trying run an expectation on a streaming service.  Could you please help us along the following two avenues:
* Could you please provide the link to the documentation for the streaming solution you are using and/or any other resources we should be aware of in order to better assess the problem?
* Could you please provide a full stack trace for the `MetricResolutionError` error that was raised?

Thank you very much again.

**Comment by austiezr** [comment]
Hey @chhayavishwakarma; Great Expectations does not support streaming use cases -- we recommend producing cadenced batches from your streaming source for use with Great Expectations if possible. Closing this out for now as unsupported.
