### ISSUE TITLE
Creating Normalized Asset Name is Slow on Production DW

### ISSUE THREAD

**Issue by saurabhnmishra** [fivetran/great_expectations#971]
Hi Team,
For one of the use cases, I'm using GE to validate the dataset from a redshift table. 
It appears to me that the below code performs a lookup on the entire redshift warehouse and that slows down things.
`data_asset_name = "redshift_table_name" # TODO: replace with your value!
normalized_data_asset_name = context.normalize_data_asset_name(data_asset_name)
normalized_data_asset_name`
 When I'm connected to my local database, it runs quite fast. I believe the lookup is slow because of the size of the production datawarehouse. So, a feature to quickly generate the normalized data asset name by providing explicit values would be great. I can type in the schema name and table name. 
Let me know if there is any other trick to this quickly move over this trivial step.

**Comment by jcampbell** [comment]
You're absolutely right about the underlying cause. Partly it's the redshift-specific dialect driver that fetches *all* metadata about the database in order to avoid lots of queries, but that is counterproductive in our case when we know we want less.

There *is* a way to explicitly specify the name so that normalization is short-circuited: provide all three components of the name (datasource, generator, and generator asset).

So, for example, in your case instead of:
`data_asset_name = "redshift_table_name"` you could use
`data_asset_name = "edw_datasource/my_table_generator/redshift_table_name"`

Now, I very much realize that that's potentially confusing (happy to hop on a call to walk through it), and I'm happy to note that I'm actively working on completely changing the way that data_asset_name is specified in the future so that it is much more explicit. But for now, that should at least eliminate the slowdown.

**Comment by saurabhnmishra** [comment]
Thanks, James. The short circuit trick works like a charm.
